### ISSUE TITLE
Ingress/Egress index override

### ISSUE THREAD

**Issue by dnlbck** [aabc/ipt-netflow#101]
Is it possible to override SNMP Interface Index for both Ingress and Egress on Netflow 5?  Currently incoming traffic shows the correct incoming interface while the outgoing interface is 65535, which makes sense as its not flowing to another interface; unfortunately this makes my collector choke as it can't find interface index 65535.  Ideally I'd want them to be the same.  Can this be done with snmp-rules?  Thank you.

**Comment by aabc** [comment]
You can not set one interface to be same as another interface with snmp-rules. Also this would be incorrect behavior of probe to lie in such a way.
