### ISSUE TITLE
does not build on latest Arch

### ISSUE THREAD

**Issue by jayray-git** [aabc/ipt-netflow#106]
This may be an easy fix, but I don't know where to start. "unable to initialize decompress status for section .debug_info" This is also being patched for the distro, please see https://aur.archlinux.org/packages/ipt-netflow-dkms-git for more details and thank you.

DKMS make.log for ipt-netflow-r339.940c61a for kernel 4.19.10-arch1-1-ARCH (x86_64)
Fri Dec 21 00:35:13 EST 2018
Compiling for kernel 4.19.10-arch1-1-ARCH
make -C /usr/lib/modules/4.19.10-arch1-1-ARCH/build M=/var/lib/dkms/ipt-netflow/r339.940c61a/build modules CONFIG_DEBUG_INFO=y
make[1]: warning: jobserver unavailable: using -j1. Add '+' to parent make rule.
make[1]: Entering directory '/usr/lib/modules/4.19.10-arch1-1-ARCH/build'
CC [M] /var/lib/dkms/ipt-netflow/r339.940c61a/build/ipt_NETFLOW.o
objdump: /var/lib/dkms/ipt-netflow/r339.940c61a/build/.tmp_ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
objdump: /var/lib/dkms/ipt-netflow/r339.940c61a/build/.tmp_ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
objdump: /var/lib/dkms/ipt-netflow/r339.940c61a/build/.tmp_ipt_NETFLOW.o: file format not recognized
Building modules, stage 2.
MODPOST 1 modules
CC /var/lib/dkms/ipt-netflow/r339.940c61a/build/ipt_NETFLOW.mod.o
LD [M] /var/lib/dkms/ipt-netflow/r339.940c61a/build/ipt_NETFLOW.ko
ld: /var/lib/dkms/ipt-netflow/r339.940c61a/build/ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
ld: /var/lib/dkms/ipt-netflow/r339.940c61a/build/ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
ld: /var/lib/dkms/ipt-netflow/r339.940c61a/build/ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
ld: /var/lib/dkms/ipt-netflow/r339.940c61a/build/ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
/var/lib/dkms/ipt-netflow/r339.940c61a/build/ipt_NETFLOW.o: file not recognized: file format not recognized
make[2]: *** [scripts/Makefile.modpost:129: /var/lib/dkms/ipt-netflow/r339.940c61a/build/ipt_NETFLOW.ko] Error 1
make[1]: *** [Makefile:1521: modules] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.19.10-arch1-1-ARCH/build'
make: *** [Makefile:25: ipt_NETFLOW.ko] Error 2

**Comment by aabc** [comment]
This looks like tool chain problem, or unclean sources.

**Comment by jayray-git** [comment]
re-downloaded sources, make clean, made sure there were no remnants in dkms folder and still the same output.. how does one go about checking/fixing a toolchain problem?

**Comment by aabc** [comment]
Try to manually build the module from the sources first.

**Comment by jayray-git** [comment]
I get the same thing when I do a new pull/configure/make..

./configure --disable-dkms 
Kernel version: 4.19.12-arch1-1-ARCH (uname)
Kernel sources: /lib/modules/4.19.12-arch1-1-ARCH/build (found)
Checking for presence of include/linux/llist.h... Yes
Checking for presence of include/linux/grsecurity.h... No
Iptables binary version: 1.8.2 (legacy) (detected from /usr/bin/iptables)
pkg-config for version 1.8.2 (legacy) exists: No (reported: 1.8.2)
Check for working gcc: Yes (gcc)
Checking for presence of xtables.h... Yes
Searching for iptables-1.8.2 (legacy) sources..
! Can not find iptables source directory, you may try setting it with --ipt-src=
! This is not fatal error, yet. Will be just using default include dir.
Iptables include flags: none (default)
Iptables module path: /usr/lib/xtables (from libxtables.so, from binary)
Searching for net-snmp-config... Yes /usr/bin/net-snmp-config
Searching for net-snmp agent... Yes.
Creating Makefile.. done.

  If you need some options enabled run ./configure --help
  Now run: make all install

make
Compiling for kernel 4.19.12-arch1-1-ARCH
make -C /lib/modules/4.19.12-arch1-1-ARCH/build M=/root/ipt-netflow-git/ipt-netflow modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory '/usr/lib/modules/4.19.12-arch1-1-ARCH/build'
  CC [M]  /root/ipt-netflow-git/ipt-netflow/ipt_NETFLOW.o
objdump: /root/ipt-netflow-git/ipt-netflow/.tmp_ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
objdump: /root/ipt-netflow-git/ipt-netflow/.tmp_ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
objdump: /root/ipt-netflow-git/ipt-netflow/.tmp_ipt_NETFLOW.o: file format not recognized
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/ipt-netflow-git/ipt-netflow/ipt_NETFLOW.mod.o
  LD [M]  /root/ipt-netflow-git/ipt-netflow/ipt_NETFLOW.ko
ld: /root/ipt-netflow-git/ipt-netflow/ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
ld: /root/ipt-netflow-git/ipt-netflow/ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
ld: /root/ipt-netflow-git/ipt-netflow/ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
ld: /root/ipt-netflow-git/ipt-netflow/ipt_NETFLOW.o: unable to initialize decompress status for section .debug_info
/root/ipt-netflow-git/ipt-netflow/ipt_NETFLOW.o: file not recognized: file format not recognized
make[2]: *** [scripts/Makefile.modpost:129: /root/ipt-netflow-git/ipt-netflow/ipt_NETFLOW.ko] Error 1
make[1]: *** [Makefile:1521: modules] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.19.12-arch1-1-ARCH/build'
make: *** [Makefile:25: ipt_NETFLOW.ko] Error 2

**Comment by aabc** [comment]
https://bbs.archlinux.org/viewtopic.php?id=242682

**Comment by jayray-git** [comment]
Yup, this is a downstream issue.. closing.
