### ISSUE TITLE
Couldn't load target NETFLOW on kernel 4.20.6

### ISSUE THREAD

**Issue by tylerjl** [aabc/ipt-netflow#109]
Hi! Thank you for writing and supporting this module.

I've got an issue trying to use `NETFLOW` targets on some recent kernels/version of `iptables` - I've tried to debug the root cause but not coming up with much, I'm hoping you may have some ideas.

Although the module compiles for dkms and gets loaded, when I attempt to add a rule jumping to the `NETFLOW` target, it isn't found:

```
[root@charon ~]# iptables -A INPUT -j NETFLOW
iptables v1.8.2 (legacy): Couldn't load target `NETFLOW':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
```

All the typical ipt-netflow pieces seem to be functional though - the `/proc` statistics are present, module loaded, etc. Any ideas? Here's some output that may be relevant to debugging.

```
[root@charon ~]# lsmod | grep -i netflow
ipt_NETFLOW            69632  0
[root@charon ~]# uname -a
Linux charon 4.20.6-1-ARCH #1 SMP PREEMPT Thu Jan 31 21:19:55 MST 2019 aarch64 GNU/Linux
[root@charon ~]# pacman -Q ipt-netflow-dkms-git iptables
ipt-netflow-dkms-git r339.940c61a-1
iptables 1:1.8.2-1
[root@charon ~]# head -n1 /proc/net/stat/ipt_netflow
ipt_NETFLOW 2.2, srcversion 3DB5E35CB22CC537C8DD334; llist
[root@charon ~]#
```

There's some bleeding edge versions here for the kernel and iptables, but everything else seems functional - just that I can't execute commands that reference the `NETFLOW` target.

**Comment by aabc** [comment]
Hi. Thanks. Probably `libipt_NETFLOW.so` is not installed into appropriate iptables lib dir. Try to run `iptables -A INPUT -j NETFLOW` under `strace`, and look for opening `libipt_NETFLOW.so` file and note directory where it tries to open it.

**Comment by tylerjl** [comment]
That's the issue @aabc:

```
[root@charon ~]# strace iptables -A INPUT -j NETFLOW 2>&1 | grep NETFLOW
execve("/usr/bin/iptables", ["iptables", "-A", "INPUT", "-j", "NETFLOW"], 0xfffffebdee80 /* 20 vars */) = 0
newfstatat(AT_FDCWD, "/usr/lib/xtables/libipt_NETFLOW.so", 0xffffca7c13c8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/xtables/libxt_NETFLOW.so", 0xffffca7c13c8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/xtables/libipt_NETFLOW.so", 0xffffca7c1408, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/xtables/libxt_NETFLOW.so", 0xffffca7c1408, 0) = -1 ENOENT (No such file or directory)
write(2, "Couldn't load target `NETFLOW':N"..., 57Couldn't load target `NETFLOW':No such file or directory
```

Symlinking the modules to the `xtables` path resolves the issue and lets the rule get loaded. Thanks for the suggestion :+1: 

I'm on Arch, and the package I'm using does the `install` step, so for my use case, the fix lies in patching the PKGBUILD. Is there any parts of this project's `make install` that you think the same fix applies to for what seems to be the different path for iptables >= 1.8.2? If not, feel free to close this one out.

**Comment by aabc** [comment]
Iptables lib dir is determined in `configure`. I don't know how your system is arranged and why `configure` cannot determine its location properly. You may specify that directory in `configure` invocation by `--ipt-lib=` option. Or fix the `configure`.

**Comment by tylerjl** [comment]
Thanks - given that the library directory is configurable and I'm sure various distributions vary quite a bit, I'd consider the onus on the distribution packagers rather than on you. Thank you again for help debugging this!

**Comment by Dmitij** [comment]
hi. i have same problem. how you fix it?

**Comment by Dmitij** [comment]
one more make this and now work
./configure --enable-natevents
make all install
depmod
