### ISSUE TITLE
Build failure with elfutils-0.176

### ISSUE THREAD

**Issue by dharrop** [aabc/ipt-netflow#121]
ipt_netflow v2.4  fails to compile with elfutils-0.176.  I get objdump errors stating "file format not recognized".  Compiles clean with elfutils-0.173 and no other changes to build chain.  My kernel (4.19.44) compiles clean with both versions of elfutils.

Using: gcc-8.3.0 and binutils-2.32

Found this Gentoo bug report that helped me identify and temporarily correct the problem by rolling back elfutils:  https://bugs.gentoo.org/671760

**Comment by aabc** [comment]
This looks like known issue:
https://github.com/aabc/ipt-netflow/issues/113
https://github.com/aabc/ipt-netflow/issues/106

**Comment by aabc** [comment]
There is nothing I can do if your toolchain is broken. Unless you provide a fix I close issue.
