### ISSUE TITLE
mac address and vlan id in v9 and v10 templates 

### ISSUE THREAD

**Issue by willyhun** [aabc/ipt-netflow#13]
Would be fine if the src and dst mac address or vlan id available  export via v9 template.  What you think about it?

**Comment by wreckerov** [comment]
Hi there, 
I have the same situation and I already tested all patches but I can't see vlan tags :(

I did this:
brctl addbr br0
brctl addif br0 eth0 eth1
ip li set up br0
ifconfig br0 promisc

iptables -L -nv -t raw
Chain PREROUTING (policy ACCEPT 6693K packets, 7111M bytes)
 pkts bytes target     prot opt in     out     source               destination
  11M   11G NETFLOW    all  --  br0    *       0.0.0.0/0            0.0.0.0/0           NETFLOW

Chain OUTPUT (policy ACCEPT 497 packets, 106K bytes)
 pkts bytes target     prot opt in     out     source               destination


head -n4  /proc/net/stat/ipt_netflow
ipt_NETFLOW 2.0, srcversion 8F15036A695E193C0140A32; llist promisc vlan
Protocol version 9 (netflow), refresh-rate 20, timeout-rate 30, (templates 23, active 7).
Timeouts: active 15s, inactive 15s. Maxflows 2000000
Promisc hack is enabled (observed 10172369 packets, discarded 0).

For extremely clearest test I use:

**Comment by aabc** [comment]
Hi. Capture couple of packets on br0 using tcpdump and send to me (email in the README), pls.

**Comment by aabc** [comment]
Please don't edit old post with new information, as I don't get notifications.

Do you get ethernetType(256) Element in flows data? Is it valid? Can you show how you see flows in wireshark (tshark)? Also, can you `--enable-macaddress` and tell if flows contain proper mac address (while not containing vlan)? Also, can show `tcpdump -eXX` of couple of packets?

**Comment by wreckerov** [comment]
Wow, this command is brilliant: tshark -np port 2055 -O cflow. I used wireshark for the same result.

Now I have:
ipt_NETFLOW 2.0, srcversion 8F15036A695E193C0140A32; llist mac promisc vlan

And I see with "tshark -np port 2055 -O cflow":
        Flow 2
            SrcAddr: 172.16.200.2 (172.16.200.2)
            DstAddr: 172.16.200.1 (172.16.200.1)
            NextHop: 0.0.0.0 (0.0.0.0)
            SrcPort: 5001
            DstPort: 47492
            TCP Flags: 0x13
            InputInt: 24
            OutputInt: 24
            Packets: 327
            Octets: 17012
            [Duration: 5.256000000 seconds]
                StartTime: 58244.684000000 seconds
                EndTime: 58249.940000000 seconds
            Protocol: 6
            IP ToS: 0x20
            TCP OptionMap: f1000000
            Destination Mac Address: 00:0d:b9:23:e8:b4 (00:0d:b9:23:e8:b4)
            Source Mac Address: 00:0d:b9:21:22:d0 (00:0d:b9:21:22:d0)
            Ethernet Type: 2048

This packet  captured by "tcpdump -i br0 -n -nn -c 1 -eX" command is :
06:43:01.281118 00:0d:b9:23:e8:b4 > 00:0d:b9:21:22:d0, ethertype 802.1Q (0x8100), length 78: vlan 200, p 0, ethertype IPv4, 172.16.200.1.47564 > 172.16.200.2.5000: Flags [S], seq 3548667564, win 14600, options [mss 1460,sackOK,TS val 342646044 ecr 0,nop,wscale 5], length 0
        0x0000:  00c8 0800 4520 003c 03b0 4000 4006 4ec7  ....E..<..@.@.N.
        0x0010:  ac10 c801 ac10 c802 b9cc 1388 d384 5eac  ..............^.
        0x0020:  0000 0000 a002 3908 b5c6 0000 0204 05b4  ......9.........
        0x0030:  0402 080a 146c 5d1c 0000 0000 0103 0305  .....l].........


What does it mean "Ethernet Type: 2048"?

**Comment by aabc** [comment]
Thanks you. "Ethernet Type" is described at http://www.iana.org/assignments/ipfix/ipfix.xhtml as ethernetType. Btw, what you showed as `tcpdump -i br0 -n -nn -c 1 -eX` output is useless, because I asked for `-eXX` options, not `-eX`, two `-XX` is not typo but important. But, I received your email with full packet capture, so it's good after all.

**Comment by aabc** [comment]
Can you test not in PREROUTING chain, but in INPUT, or OUTPUT, or FORWARD?

**Comment by aabc** [comment]
I found that your data is contradictory. Reported _ethernetType_ have valid value for it to be parsed *after* _vlan_ tag, but _vlan_ is not reported, as if not parsed at all. Such level of inconsistency need debugging at the box, and can not be done remotely by words. Maybe you can provide access to me?

**Comment by cobravsninja** [comment]
Hello,

Is it possible to get VLAN ids of any VLAN interface (eth0.10, eth0.20, etc) by simply specifying iptables -I FORWARD -j NETFLOW rule? I tried to do that but unfortunately I can't see any VLAN related data :-( Thank you!

**Comment by cobravsninja** [comment]
I've disabled REORDER_HDR on all VLAN interfaces and it started to show VLAN ids. ipt_NETFLOW is BEST! Thank you!

**Comment by aabc** [comment]
@cobravsninja Thanks for info!

**Comment by cobravsninja** [comment]
One more thing, disabling REORDER_HDR has an impact on DHCP functionality, I'm not C programmer, but after applying [this](https://github.com/cobravsninja/ipt-netflow/commit/6366b71d8c53a9056949ce326f4511316a84dd83) little trick VLAN ids started to appear in flows. Please correct me if I'm wrong and thank you again for an amazing module :+1:

**Comment by aabc** [comment]
Interesting idea, need to think about it. Thanks.

Module shoudl restore tag with `vlan_tx_tag_get()` when kernel strips it. Maybe new kernel do differently, though.

Sometimes you may `modbrobe br_netfilter` and play with `net.bridge.bridge-nf-filter-vlan-tagged` sysctl to make kernel pass vlans to iptables (as I remember).

**Comment by aabc** [comment]
Just for reference link to `br_netfilter`: http://ebtables.netfilter.org/documentation/bridge-nf.html

**Comment by cobravsninja** [comment]
Welcome! Glad to hear that :-) One more thing, I think skb.vlan_tci is going to be cleared when REORDER_HDR is active (this is why it worked when I disabled it). After installing last version of ipt, VLAN field missed again and it appeared after disabling REORDER_HDR. After removing exclamation mark in this part of code `!(vlan->flags & VLAN_FLAG_REORDER_HDR)` it started to appear again (in both cases, with enabled and disabled REORDER_HDR). Thank you.

P.S. Sorry, forgot to mention that I've tested this stuff on 2 Linux boxes (Debian 8 3.16 kernel, IPFire 2.19 120 3.14 kernel).

**Comment by aabc** [comment]
Thanks for testing! `skb.vlan_tci` is cleared in any case. But in case `VLAN_FLAG_REORDER_HDR` is disabled (i.e. not set), vlan id is also reinjected back to the packet. When it's reinjected I don't need to extract it from `net_device`. And yes, I need to invert whole condition. Excuse me.

Soon, I will force push fix with rebase, so you will need to `git pull --rebase` to get it correctly or make fresh clone.

**Comment by aabc** [comment]
Fixed. I decided to not invert conditional with De Morgan's rules, which would simplify it, but to add outer negation to how conditional looks in `vlan_do_receive()`. This would make it looks more complicated, but simpler if we take to account it's just a copy of `if` from `vlan_do_receive()`. Thanks again!
