### ISSUE TITLE
Issues with nfcapd in ipt-netflow 2.5

### ISSUE THREAD

**Issue by nuqleo** [aabc/ipt-netflow#135]
Hello,

With new version ipt-netflow 2.5, nfcapd warnings appeared in logs that were not with previous versions:

nfcapd[4698]: Process_v9: Corrupt data flowset? Pad bytes: 36

Similar issues:
https://github.com/phaag/nfdump/issues/56
https://github.com/phaag/nfdump/issues/141

Is there something wrong with padding in  ipt-netflow 2.5 or this is nfcapd related issue?

Thanks

**Comment by aabc** [comment]
Hi. There is no change in the ipt-netflow export format between 2.4 and 2.5. Since v2.1 there is only minor and maintenance updates, see https://github.com/aabc/ipt-netflow/releases

It would be best to capture packets with possible wrong data and then analyze them.

**Comment by nuqleo** [comment]
Warnings are gone after restart of nfcapd.
Thanks and sorry for noise.
