### ISSUE TITLE
Want to send payload information along with Netflow

### ISSUE THREAD

**Issue by maazamalik** [aabc/ipt-netflow#136]
I have a SIEM on which I want to see payloads of Netflows. I thought maybe enabling promisc will serve my purpose but still i don't see any payload in the field or maybe i am doing something wrong. I just want to ask if there's any way to achieve this task from ipt-Netflow?

**Comment by aabc** [comment]
> i don't see any payload in the field

What 'field' do you mean?

**Comment by maazamalik** [comment]
So in my SIEM solution, whenever i open a flow record, it displays many fields such as source/destination IP/port along with a field named 'Payload' which is blank. So i just wanted to ask if ipt-netflow could send payload information or if not the payload, just the request that has been sent like "curl command" or "wget".

**Comment by aabc** [comment]
I don't know anything about solutions, and only concerned about low-level netflow/ipfix protocol. Sorry.
