### ISSUE TITLE
Debian 10, accel-ppp, ipt_NETFLOW

### ISSUE THREAD

**Issue by Biss81** [aabc/ipt-netflow#141]
Добрый день!
Gодскажите! Есть у меня в продакшене дав старых сервера:

Intel Q9550, 4Gb, Intel E1G42BT. Текущая конфиграция Debian 7 (3.14.34), accel-ppp 1.8.0, ipt_NETFLOW 2.1.

Все прекрасно работает пережевывает 1,5к клиентов на сервер в нагрузук 1,5 Gbps трафика.

Вроде бы пришла пора заапгредится. Ставлю Debian 10.4 (тест был на родном ядре и ядре 4.19.123), последний accel из git и ipt_NETFLOW из git, только становится чуть больше pps срабатывает watchdog.

При отключении всякого в ядре, я увидел, что accel сжирает ядро на 100%, вываливаются BUG: soft lockup - CPU#0 stuck for 22s!

Экспериментальным путем пришел к тому, что при выгрузке ipt_NETFLOW, все работает нормально.

ipt_NETFLOW загружается только с параметром указания коллектора.
 
Проверял на обеих серверах
![screen](https://user-images.githubusercontent.com/67321068/85398874-e4509780-b566-11ea-9cda-cfba0acc8356.png)
[kern.log.gz](https://github.com/aabc/ipt-netflow/files/4819035/kern.log.gz)

Прилагаю kern.log и скрин с экрана сервера

**Comment by aabc** [comment]
Hi. А пришлите, пожалуйста, бинарник собранного модуля с исходниками из которых он собран. Это нужно, чтоб заресолвить символы `netflow_target+0x248` и `netflow_target+0x35b`.

Или сами попробуйте  сделать так:
```
# gdb ipt_NETFLOW.ko
(gdb) l *netflow_target+0x248
(gdb) l *netflow_target+0x35b
```
Детальнее примеры тут: https://www.kernel.org/doc/html/v4.15/admin-guide/bug-hunting.html

**Comment by Biss81** [comment]
Вкладываю скомпилированный сорцы

Вывод команд вот такой:

(gdb) l *netflow_target+0x248
0x4ab8 is in netflow_target (/usr/src/ipt-netflow/ipt_NETFLOW.c:5245).
5240    #endif
5241            read_lock(&htable_rwlock);
5242            stripe = &htable_stripes[hash & LOCK_COUNT_MASK];
5243            spin_lock(&stripe->lock);
5244            /* record */
5245            nf = ipt_netflow_find(&tuple, hash);
5246            if (unlikely(!nf)) {
5247                    struct rtable *rt;
5248
5249                    if (unlikely(maxflows > 0 && atomic_read(&ipt_netflow_count) >= maxflows)) {

(gdb) l *netflow_target+0x35b
0x4bcb is in netflow_target (./arch/x86/include/asm/atomic.h:167).
162      *
163      * Atomically adds @i to @v and returns @i + @v
164      */
165     static __always_inline int arch_atomic_add_return(int i, atomic_t *v)
166     {
167             return i + xadd(&v->counter, i);
168     }
169
170     /**
171      * arch_atomic_sub_return - subtract integer and return
[ipt-netflow.tar.gz](https://github.com/aabc/ipt-netflow/files/4820072/ipt-netflow.tar.gz)

**Comment by aabc** [comment]
Спасибо!

**Comment by pbspb** [comment]
У меня на сервере debian 10.4 (x64) без accel-ppp, просто две сетевухи (Hyper-V, E5-2643, 2Gb) виснет наглухо виртуалка, если загружен модуль ipt_netflow и есть правила в iptables. Данные ловит flow-capture на той же машине.
Аналогичная система но на i686 (4.19.0-8-686-pae #1 SMP Debian 4.19.98-1 (2020-01-26) i686 GNU/Linux) работает стабильно.

![изображение](https://user-images.githubusercontent.com/67702540/86266298-ad652c00-bbcd-11ea-9b53-ab3d759e7a2e.png)


4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux


filename:       /lib/modules/4.19.0-9-amd64/updates/dkms/ipt_NETFLOW.ko
alias:          ip6t_NETFLOW
version:        2.2
description:    iptables NETFLOW target module
author:         <abc@telekom.ru>
license:        GPL
srcversion:     6282F494B5DAD5E28A24126
depends:        x_tables,nf_conntrack
retpoline:      Y
name:           ipt_NETFLOW
vermagic:       4.19.0-9-amd64 SMP mod_unload modversions 
parm:           destination:export destination ipaddress:port (charp)
parm:           sampler:flow sampler parameters (charp)
parm:           inactive_timeout:inactive flows timeout in seconds (int)
parm:           active_timeout:active flows timeout in seconds (int)
parm:           exportcpu:lock exporter to this cpu (int)
parm:           promisc:enable promisc hack (0=default, 1) (int)
parm:           debug:debug verbosity level (int)
parm:           sndbuf:udp socket SNDBUF size (int)
parm:           protocol:netflow protocol version (5, 9, 10=IPFIX) (int)
parm:           refresh_rate:NetFlow v9/IPFIX refresh rate (packets) (uint)
parm:           timeout_rate:NetFlow v9/IPFIX timeout rate (minutes) (uint)
parm:           scan_min:Minimal interval between export scans (jiffies) (uint)
parm:           snmp_rules:SNMP-index conversion rules (charp)
parm:           natevents:enable NAT Events (int)
parm:           hashsize:hash table size (int)
parm:           maxflows:maximum number of flows (int)
parm:           engine_id:Observation Domain ID (int)

**Comment by Biss81** [comment]
На текйщиу момень я смог решить проблему пересборкой ядра с параметром HZ=1000, пока вроде все хорошо, но на сколько это корректно

**Comment by aabc** [comment]
Я понял так:

1й случай:

- Debian 7 ядро 3.14.34 - ipt_NETFLOW 2.1 - работает ок.
- Debian 10.4 ядро 4.19.123 (с NOHZ) - ipt_NETFLOW 2.5-2-g8f06203 - soft lockup.
- То же самое с HZ=1000 - работает стабильно.

2й случай:

- Debian 10.4 amd64 4.19.118-2+deb10u1 - ipt_NETFLOW 2.2 - soft lockup.
- Debian 10.4 i686 ядро 4.19.98-1 - ipt_NETFLOW 2.2 - работает стабильно.

По второму: версия 2.2 это 2015 год, не могли бы вы протестировать на 2.5?

И если у вас есть возможность тестировать на вашей конфигурации, то не могли бы вы собрать (или поставить) -debug ядро? Там есть анализаторы который могут вывести в dmesg полезную информацию.

**Comment by Biss81** [comment]
По первому случаю посмотрел, 4.19.123 собиралось с конфигом от ядра debian
там стоит HZ=250 по умолчанию

**Comment by aabc** [comment]
Пытаюсь воспроизвести проблему, но не получается.

У вас в трейсе есть строки:
```
Jun 22 14:23:36 as26 kernel: [12718.488487]  ? netflow_target+0x35b/0x1040 [ipt_NETFLOW]
Jun 22 14:23:36 as26 kernel: [12718.488493]  ? nft_target_eval_xt+0x35/0x50 [nft_compat]
```
Я думаю, это значит, что у вас ipt_NETFLOW вызывается не из iptables, а из nftables. Как вы ставите правила?

**Comment by aabc** [comment]
По поводу -debug ядра, его похоже нет в Debian. Если захотите собрать ядро сами то - (не на продакшен сервере, так как, возможно, это его сильно замедлит) - включите опции:
```
CONFIG_DEBUG_KERNEL=y
CONFIG_LOCK_DEBUGGING_SUPPORT=y
CONFIG_PROVE_LOCKING=y
CONFIG_DEBUG_SPINLOCK=y
CONFIG_FRAME_POINTER=y
CONFIG_LOCKDEP=y
CONFIG_DEBUG_ATOMIC_SLEEP=y
```

**Comment by Biss81** [comment]
Похоже так и есть. Правила загружаются через iptables-persistent.
iptables идет симлинком на /usr/sbin/iptables-nft
Тогда вопрос, как правильнее поступить?

**Comment by aabc** [comment]
1. Я не пользовался nftables.
2. У меня нет решения, так как на данный момент не известно в чем проблема. Надо искать. Или вы можете помочь в поисках, или я должен воспроизвести проблему (пока безуспешно).

**Comment by pbspb** [comment]
К сожалению, у меня нет возможности поставить -debug ядро и тестировать не на продакшене.

**Comment by Biss81** [comment]
> 1. Я не пользовался nftables.
> 2. У меня нет решения, так как на данный момент не известно в чем проблема. Надо искать. Или вы можете помочь в поисках, или я должен воспроизвести проблему (пока безуспешно).

Постараюсь заменить сервер, на котором четко воспроизводится ситуация и поставить туда дебаг, по мере возможности.
Надо еще понять, как его правильно сложить без нагрузки.

А про рекомендации, я интересовался как раз про тактовое и безтактовое ядро.

**Comment by aabc** [comment]
> А про рекомендации, я интересовался как раз про тактовое и безтактовое ядро.

> NOHZ или какой то определенный HZ?

Отвечаю: я не знаю, так как не известно в чем проблема, я не могу давать советов по решению не известно чего. Проблемы быть не должно ни на каких видах ядер, но она есть.

**Comment by Biss81** [comment]
> > А про рекомендации, я интересовался как раз про тактовое и безтактовое ядро.
> 
> > NOHZ или какой то определенный HZ?
> 
> Отвечаю: я не знаю, так как не известно в чем проблема, я не могу давать советов по решению не известно чего. Проблемы быть не должно ни на каких видах ядер, но она есть.

Спасибо! Все принял. Буду делать тестовый стенд!
Вы делаете большую работу и за это мы Вам благодарны!
Постараемся помочь со своей стороны в ее развитии.

**Comment by aabc** [comment]
Сделал фикс, пожалуйста проверьте стало ли ок.

**Comment by aabc** [comment]
Изменения с багфиксом в git -- то есть надо сделать или `git pull`, или `git clone` заново. Был бы благодарен, если бы вы сообщили результаты тестирования.

**Comment by Biss81** [comment]
Отличная новость! Завтра ставлю в тест. По результатам сообщу 10.08.2020, 04:30, "ABC" <notifications@github.com>: Изменения с багфиксом в git -- то есть надо сделать или git pull, или git clone заново. Был бы благодарен, если бы вы сообщили результаты тестирования.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Biss81** [comment]
Работаю сутки. Все отлично!  10.08.2020, 04:30, "ABC" <notifications@github.com>: Изменения с багфиксом в git -- то есть надо сделать или git pull, или git clone заново. Был бы благодарен, если бы вы сообщили результаты тестирования.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aabc** [comment]
@Biss81 Спасибо!
