### ISSUE TITLE
make all install in CentOS 8 not working

### ISSUE THREAD

**Issue by jamezbond13** [aabc/ipt-netflow#143]
./configure
Kernel version: 4.18.0-193.14.2.el8_2.x86_64 (uname)
Kernel sources: /lib/modules/4.18.0-193.14.2.el8_2.x86_64/build (found)
Checking for presence of include/linux/netfilter.h... Yes
netfilter.h uses CONFIG_NF_NAT_NEEDED... Yes
Checking for presence of include/linux/llist.h... Yes
Checking for presence of include/linux/grsecurity.h... No
Iptables binary version: 1.8.4 (nf_tables) (detected from /usr/sbin/iptables)
pkg-config for version 1.8.4 (nf_tables) exists: No (reported: 1.8.4)
Check for working gcc: Yes (gcc)
Checking for presence of xtables.h... Yes
Searching for iptables-1.8.4 (nf_tables) sources..
! Can not find iptables source directory, you may try setting it with --ipt-src=
! This is not fatal error, yet. Will be just using default include dir.
Iptables include flags: none (default)
Iptables module path: /usr/lib64/xtables (from libxtables.so, from binary)
Searching for net-snmp-config... Yes /usr/bin/net-snmp-config
Searching for net-snmp agent... Yes.
Checking for DKMS... Yes.
Creating Makefile.. done.

  If you need some options enabled run ./configure --help
  Now run: make all install
make all install
Compiling for kernel 4.18.0-193.14.2.el8_2.x86_64
make -C /lib/modules/4.18.0-193.14.2.el8_2.x86_64/build M=/root/ipt-netflow-2.5                                                                                           modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory '/usr/src/kernels/4.18.0-193.14.2.el8_2.x86_64'
  CC [M]  /root/ipt-netflow-2.5/ipt_NETFLOW.o
/root/ipt-netflow-2.5/ipt_NETFLOW.c: In function ‘ipt_netflow_fini’:
/root/ipt-netflow-2.5/ipt_NETFLOW.c:5787:2: error: implicit declaration of funct                                                                                          ion ‘synchronize_sched’; did you mean ‘synchronize_net’? [-Werror=implicit-funct                                                                                          ion-declaration]
  synchronize_sched();
  ^~~~~~~~~~~~~~~~~
  synchronize_net
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:319: /root/ipt-netflow-2.5/ipt_NETFLOW.o] E                                                                                          rror 1
make[1]: *** [Makefile:1545: _module_/root/ipt-netflow-2.5] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.18.0-193.14.2.el8_2.x86_64'
make: *** [Makefile:25: ipt_NETFLOW.ko] Error 2

Im stuck in here and cant do anything. Please help me to solve this issue. 
I've also tried to make all instal in ipt_netflow v.2-3 and there was no differnce.

**Comment by aabc** [comment]
Fixed in git head. Pls, `git pull --rebase` or do a fresh `git clone`.
