### ISSUE TITLE
Error to build with --enable-physdev

### ISSUE THREAD

**Issue by willhalen5150** [aabc/ipt-netflow#144]
Hello! I have the same problem to build with this option --enable-physdev

#130 

./configure --enable-natevents --enable-macaddress --enable-vlan --enable-direction --enable-promisc --promisc-mpls --enable-physdev --disable-dkms --disable-dkms-install --kdir=/usr/src/kernels/3.10.0-957.10.1.el7.x86_64/
Kernel version: 3.10.0-957.10.1.el7.x86_64 (sources)
Kernel sources: /usr/src/kernels/3.10.0-957.10.1.el7.x86_64/ (requested)
Checking for presence of include/linux/netfilter.h... Yes
netfilter.h uses CONFIG_NF_NAT_NEEDED... Yes
Checking for presence of include/linux/llist.h... Yes
Checking for presence of include/linux/grsecurity.h... No
Iptables binary version: 1.4.21 (detected from /sbin/iptables)
pkg-config for version 1.4.21 exists: Yes
Check for working gcc: Yes (gcc)
Checking for presence of xtables.h... Yes (using pkg-config)
Iptables include flags:   (pkg-config)
Iptables module path: /usr/lib64/xtables (pkg-config)
Searching for net-snmp-config... No.
Searching for net-snmp agent... No.
 Assuming you don't want net-snmp agent support.
 Otherwise do:  yum install net-snmp net-snmp-devel
Creating Makefile.. done.

  If you need some options enabled run ./configure --help
  Now run: make all install

make output

./gen_compat_def > compat_def.h
Compiling for kernel 3.10.0-957.10.1.el7.x86_64
make -C /usr/src/kernels/3.10.0-957.10.1.el7.x86_64/ M=/home/test/rpmbuild/BUILD/ipt-netflow-2.5 modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
  CC [M]  /home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.o
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c: In function 'netflow_target':
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5292:3: error: implicit declaration of function 'nf_bridge_info_get' [-Werror=implicit-function-declaration]
   copy_dev(nf->o_ifphys, physoutdev, if_out);
   ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5287:57: error: invalid type argument of '->' (have 'int')
   if (nf_bridge_info_get(skb) && nf_bridge_info_get(skb)->physdev) \
                                                         ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5292:3: note: in expansion of macro 'copy_dev'
   copy_dev(nf->o_ifphys, physoutdev, if_out);
   ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5288:46: error: invalid type argument of '->' (have 'int')
    out = resolve_snmp(nf_bridge_info_get(skb)->physdev); \
                                              ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5283:30: note: in definition of macro 'resolve_snmp'
 # define resolve_snmp(dev) ((dev)? (dev)->ifindex : -1)
                              ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5292:3: note: in expansion of macro 'copy_dev'
   copy_dev(nf->o_ifphys, physoutdev, if_out);
   ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5288:46: error: invalid type argument of '->' (have 'int')
    out = resolve_snmp(nf_bridge_info_get(skb)->physdev); \
                                              ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5283:37: note: in definition of macro 'resolve_snmp'
 # define resolve_snmp(dev) ((dev)? (dev)->ifindex : -1)
                                     ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5292:3: note: in expansion of macro 'copy_dev'
   copy_dev(nf->o_ifphys, physoutdev, if_out);
   ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5287:57: error: invalid type argument of '->' (have 'int')
   if (nf_bridge_info_get(skb) && nf_bridge_info_get(skb)->physdev) \
                                                         ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5293:3: note: in expansion of macro 'copy_dev'
   copy_dev(nf->i_ifphys, physindev, if_in);
   ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5288:46: error: invalid type argument of '->' (have 'int')
    out = resolve_snmp(nf_bridge_info_get(skb)->physdev); \
                                              ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5283:30: note: in definition of macro 'resolve_snmp'
 # define resolve_snmp(dev) ((dev)? (dev)->ifindex : -1)
                              ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5293:3: note: in expansion of macro 'copy_dev'
   copy_dev(nf->i_ifphys, physindev, if_in);
   ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5288:46: error: invalid type argument of '->' (have 'int')
    out = resolve_snmp(nf_bridge_info_get(skb)->physdev); \
                                              ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5283:37: note: in definition of macro 'resolve_snmp'
 # define resolve_snmp(dev) ((dev)? (dev)->ifindex : -1)
                                     ^
/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.c:5293:3: note: in expansion of macro 'copy_dev'
   copy_dev(nf->i_ifphys, physindev, if_in);
   ^
cc1: some warnings being treated as errors
make[2]: *** [/home/test/rpmbuild/BUILD/ipt-netflow-2.5/ipt_NETFLOW.o] Error 1
make[1]: *** [_module_/home/test/rpmbuild/BUILD/ipt-netflow-2.5] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-957.10.1.el7.x86_64'
make: *** [ipt_NETFLOW.ko] Error 2

System Configuration:
CentOS Linux release 7.6.1810 (Core)

3.10.0-957.10.1.el7.x86_64

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

Someone know how can I fix this problem?

Thanks a lot

**Comment by aabc** [comment]
Thanks for the report! It seems to be centos related. I will look to it a bit later.

**Comment by aabc** [comment]
Cannot reproduce on git version. I think you are using old 2.5 version. Please **reopen** if it's reproducible for you on git version.
