### ISSUE TITLE
DKMS build error with repo 2.5.1 tag

### ISSUE THREAD

**Issue by pwp333** [aabc/ipt-netflow#148]
OS: Ubuntu 18.04
Kernel: 4.18.0-1024
gcc: version 7.4.0

/var/lib/dkms/ipt-netflow/2.5/build/ipt_NETFLOW.c:5289:7: error: implicit declaration of function ‘nf_bridge_info_get’; did you mean ‘nf_bridge_get’? [-Werror=implicit-function-declaration]
   if (nf_bridge_info_get(skb) && nf_bridge_info_get(skb)->physdev) \
       ^
/var/lib/dkms/ipt-netflow/2.5/build/ipt_NETFLOW.c:5294:3: note: in expansion of macro ‘copy_dev’
   copy_dev(nf->o_ifphys, physoutdev, if_out);
   ^~~~~~~~
/var/lib/dkms/ipt-netflow/2.5/build/ipt_NETFLOW.c:5289:57: error: invalid type argument of ‘->’ (have ‘int’)
   if (nf_bridge_info_get(skb) && nf_bridge_info_get(skb)->physdev) \
                                                         ^
/var/lib/dkms/ipt-netflow/2.5/build/ipt_NETFLOW.c:5294:3: note: in expansion of macro ‘copy_dev’
   copy_dev(nf->o_ifphys, physoutdev, if_out);
   ^~~~~~~~
/var/lib/dkms/ipt-netflow/2.5/build/ipt_NETFLOW.c:5290:46: error: invalid type argument of ‘->’ (have ‘int’)
    out = resolve_snmp(nf_bridge_info_get(skb)->physdev); \
                                              ^
/var/lib/dkms/ipt-netflow/2.5/build/ipt_NETFLOW.c:5294:3: note: in expansion of macro ‘copy_dev’
   copy_dev(nf->o_ifphys, physoutdev, if_out);
   ^~~~~~~~
/var/lib/dkms/ipt-netflow/2.5/build/ipt_NETFLOW.c:5289:57: error: invalid type argument of ‘->’ (have ‘int’)
   if (nf_bridge_info_get(skb) && nf_bridge_info_get(skb)->physdev) \
                                                         ^
/var/lib/dkms/ipt-netflow/2.5/build/ipt_NETFLOW.c:5295:3: note: in expansion of macro ‘copy_dev’
   copy_dev(nf->i_ifphys, physindev, if_in);
   ^~~~~~~~

**Comment by aabc** [comment]
This is already fixed in git version.
