### ISSUE TITLE
softlockup

### ISSUE THREAD

**Issue by splitice** [aabc/ipt-netflow#160]
Hi,

I maintain a fork of ipt-netflow (currently no pull requests, it's not suitable) which i eventually plan to spin off into a different module.

I was wondering if you knew why commit 653a52aa1d7a338aabfc99e3938f2a00da1385f0 was a deadlock? I could not for the life of me find the other party to deadlock.

I was able to reproduce the deadlock with
```
while [[ true ]]; do
        iptables -I PREROUTING -t raw -j NETFLOW
        iptables -I PREROUTING -t raw -j NETFLOW
        iptables -I PREROUTING -t raw -j NETFLOW
        iptables -I PREROUTING -t raw -j NETFLOW
        iptables -I PREROUTING -t raw -j NETFLOW
        iptables -I PREROUTING -t raw -j NETFLOW
        iptables -I PREROUTING -t raw -j NETFLOW
        iptables -I PREROUTING -t raw -j NETFLOW
        iptables -F PREROUTING -t raw
done
```

It does appear that commit fixes the issue, I'm just unsure why.

**Comment by aabc** [comment]
It's because nftables calls xtables targets for OUTPUT traffic not in softirq context (unlike how native xtables call them - which is always softirq context). This difference in types of contexts caused deadlock.

**Comment by splitice** [comment]
If that's all it is then I am surpised that commit fixed the issue I saw since I saw it in xtables.

I'll need to repeat my test (perhaps for longer) and see if the issue is actually still there.

**Comment by aabc** [comment]
This commit is surely fixes the issue, not causes it.

**Comment by splitice** [comment]
Thank you @aabc for taking the time to answer my questions. I'll continue poking around and see what I can find. If what i find relates to the upstream module I'll be sture to report it.

Have a great weekend.
