### ISSUE TITLE
Bulid failed on kernel 5.10.8

### ISSUE THREAD

**Issue by JoyHusky** [aabc/ipt-netflow#163]
![image](https://user-images.githubusercontent.com/34576357/106855629-6f8e3000-66e7-11eb-9bbc-9d3c7277f669.png)

$ ./configure --enable-natevents --enable-macaddress --enable-aggregation
...
Now run: make all install

$ LANG=C make
Compiling for kernel 5.10.8-arch1-1
make -C /lib/modules/5.10.8-arch1-1/build M=/home/joy/build/ipt-netflow modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory '/usr/lib/modules/5.10.8-arch1-1/build'
  CC [M]  /home/joy/build/ipt-netflow/ipt_NETFLOW.o
In file included from /home/joy/build/ipt-netflow/ipt_NETFLOW.c:76:
/home/joy/build/ipt-netflow/ipt_NETFLOW.c: In function 'register_ct_events':
/home/joy/build/ipt-netflow/compat.h:173:21: error: implicit declaration of function 'ref_module'; did you mean 'use_module'? [-Werror=implicit-function-declaration]
  173 | # define use_module ref_module
      |                     ^~~~~~~~~~
/home/joy/build/ipt-netflow/ipt_NETFLOW.c:5480:3: note: in expansion of macro 'use_module'
 5480 |   use_module(THIS_MODULE, netlink_m);
      |   ^~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /home/joy/build/ipt-netflow/ipt_NETFLOW.o] Error 1
make[1]: *** [Makefile:1805: /home/joy/build/ipt-netflow] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.10.8-arch1-1/build'
make: *** [Makefile:25: ipt_NETFLOW.ko] Error 2

**Comment by aabc** [comment]
Hello. Because, it's hard to predict the future and impossible to change past. I suggest to use latest git version to build the module. It should compile good on 5.10.8 defconfig.

**Comment by JoyHusky** [comment]
Hello! Thank you
