### ISSUE TITLE
Ubuntu 20.10 Compatability?

### ISSUE THREAD

**Issue by cbc02009** [aabc/ipt-netflow#170]
I'm pretty sure I read that Ubuntu now uses nftables by default instead of iptables and provides an iptables shim layer for compatability. I'm still relatively new to networking stuff, so I apologize if this is a dumb question, but does this mean that this kernel module won't work on a router running 20.10?

**Comment by aabc** [comment]
It could work as long as it supports iptables, please try.

**Comment by tugik** [comment]
Same question but about the future Debian 11
I get an error,  and I think it will be same in Ubuntu20.10


like this

#make
***********skip*******
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.10.0-5-common/scripts/Makefile.build:284: /usr/src/ipt-netflow-code/ipt_NETFLOW.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.10.0-5-common/Makefile:1819: /usr/src/ipt-netflow-code] Error 2
make[1]: *** [/usr/src/linux-headers-5.10.0-5-common/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-5-amd64'
make: *** [Makefile:25: ipt_NETFLOW.ko] Error 2
#

**Comment by cbc02009** [comment]
Sorry, haven't had a chance to work on this yet. I'll give it a shot when I can.

**Comment by aabc** [comment]
`nftables` can use `iptables` targets/modules, and people reported this configuration in some distros. It should work as is in that compatibility mode (I think kernel should have `CONFIG_NFT_COMPAT` enabled*). But, it won't work as native nft module (since it does not support user-space extensions).

* Description of `CONFIG_NFT_COMPAT`:
```
config NFT_COMPAT
        depends on NETFILTER_XTABLES
        tristate "Netfilter x_tables over nf_tables module"
        help
          This is required if you intend to use any of existing
          x_tables match/target extensions over the nf_tables
          framework.
```
This should work.
