### ISSUE TITLE
After kernel update i cant make install in Centos 8

### ISSUE THREAD

**Issue by jamezbond13** [aabc/ipt-netflow#178]
Package kernel-devel-4.18.0-305.7.1.el8_4.x86_64 is already installed.

[root@uz ipt-netflow]# ./configure
Module version: 2.6-1-g352cdb2
Kernel version: 4.18.0-305.7.1.el8_4.x86_64 (uname)
Kernel sources: /lib/modules/4.18.0-305.7.1.el8_4.x86_64/build (found)
Checking for presence of include/linux/netfilter.h... Yes
netfilter.h uses CONFIG_NF_NAT_NEEDED... Yes
Checking for presence of include/linux/llist.h... Yes
Checking for presence of include/linux/grsecurity.h... No
Iptables binary version: 1.8.4 (nf_tables) (detected from /usr/sbin/iptables)
pkg-config for version 1.8.4 (nf_tables) exists: No (reported: 1.8.4)
Check for working gcc: Yes (gcc)
Checking for presence of xtables.h... Yes
Searching for iptables-1.8.4 (nf_tables) sources..
! Can not find iptables source directory, you may try setting it with --ipt-src=
! This is not fatal error, yet. Will be just using default include dir.
Iptables include flags: none (default)
Iptables module path: /usr/lib64/xtables (from libxtables.so, from binary)
Searching for net-snmp-config... Yes /usr/bin/net-snmp-config
Searching for net-snmp agent... Yes.
Checking for DKMS... Yes.
Creating Makefile.. done.

  If you need some options enabled run ./configure --help
  Now run: make all install

[root@uz ipt-netflow]# make all install
./gen_compat_def > compat_def.h
Test symbol xt_family linux/netfilter_ipv4/ip_tables.h  declared
Test struct timeval linux/ktime.h  declared
Test struct proc_ops linux/proc_fs.h  undeclared
Test symbol synchronize_sched linux/rcupdate.h  undeclared
Test symbol nf_bridge_info_get linux/netfilter_bridge.h  declared
Test struct vlan_dev_priv linux/if_vlan.h  declared
Compiling 2.6-1-g352cdb2 for kernel 4.18.0-305.7.1.el8_4.x86_64
make -C /lib/modules/4.18.0-305.7.1.el8_4.x86_64/build M=/root/ipt-netflow modules
make[1]: Entering directory '/usr/src/kernels/4.18.0-305.7.1.el8_4.x86_64'
  CC [M]  /root/ipt-netflow/ipt_NETFLOW.o
/root/ipt-netflow/ipt_NETFLOW.c:3536:20: error: conflicting types for ‘put_unaligned_be24’
 static inline void put_unaligned_be24(u32 val, unsigned char *p)
                    ^~~~~~~~~~~~~~~~~~
In file included from ./arch/x86/include/asm/unaligned.h:10,
                 from ./include/linux/etherdevice.h:29,
                 from ./include/linux/if_vlan.h:16,
                 from ./include/linux/filter.h:22,
                 from ./include/net/sock.h:64,
                 from ./include/net/inet_sock.h:26,
                 from ./include/linux/udp.h:20,
                 from /root/ipt-netflow/ipt_NETFLOW.c:33:
./include/linux/unaligned/generic.h:98:20: note: previous definition of ‘put_unaligned_be24’ was here
 static inline void put_unaligned_be24(const u32 val, void *p)
                    ^~~~~~~~~~~~~~~~~~
/root/ipt-netflow/ipt_NETFLOW.c: In function ‘ipt_netflow_init’:
/root/ipt-netflow/ipt_NETFLOW.c:5618:43: error: invalid operands to binary << (have ‘long unsigned int (*)(void)’ and ‘int’)
   unsigned long memksize = (num_physpages << PAGE_SHIFT) / 1024;
                                           ^~
make[2]: *** [scripts/Makefile.build:322: /root/ipt-netflow/ipt_NETFLOW.o] Error 1
make[1]: *** [Makefile:1563: _module_/root/ipt-netflow] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.18.0-305.7.1.el8_4.x86_64'
make: *** [Makefile:27: ipt_NETFLOW.ko] Error 2

Помогите пожалуйста, Please help.

**Comment by aabc** [comment]
I did some fix, can you please test?

**Comment by jamezbond13** [comment]
Thanks for the quick response! Everything was installed without problems and started. Thanks again for your help!
