### ISSUE TITLE
Sampling Rate Doesn't  Show Up In Data Template

### ISSUE THREAD

**Issue by tom-x1** [aabc/ipt-netflow#185]
We are using version 2.5.1 on Ubuntu 18.04 with kernel 5.4.0-81

Overall we are very pleased with this module, it works like expected but there seems to be an issue with reporting the sampling rate to the collector as the template transmitted by the exporter doesn't contain the configured sampling rate. This is the config we are using on our exporter:

`
options ipt_NETFLOW destination=1.2.3.4:2055 protocol=9 natevents=1 maxflows=0 active_timeout=60 inactive_timeout=3 sndbuf=851968 engine_id=939820 sampler=deterministic:20
`

So as you can see we are using a deterministic sampling rate of 1:20. As per the following document: https://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html the exporter should (along with other information) report the configured sampling mechanism and rate via template using the fields: **SAMPLING_ALGORITHM** and **SAMPLING_INTERVAL**.
Unfortunately it seems that it doesn't, those fields are missing.

I've ran tcpdump to record some of the exported flow traffic and saved it to a pcap file, afterwards I've opened this file in Wireshark to do a deeper analysis. Allthough templates are transmitted regulary, it seems that they never contain any information about the used sampling mechanism and rate. Here's an example of which fields are reported... the count is always between 21 and 23 fields (screenshot from Wireshark):

![2021-11-16_141416](https://user-images.githubusercontent.com/28628667/141993354-67a487a8-d635-4af5-8e13-7d15a4419b5a.jpg)

**Comment by tom-x1** [comment]
Ok I Just learned that it does not export sample rate with each template export but only every ~10th template export. So no issue at all :)

**Comment by tom-x1** [comment]
Sorry reopening it again because I'm asking myself if this is really the correct behaviour. 

Shouldn't the exporter report it's sampling rate (and type) with every exported template? Lets assume the collector is using the sampling rate setting inside the template to calculate the correct pps, bytes and so on automatically... if the sampling rate is not included within each template export, then the collector would permanently flap between calculating values with and without sampling rate? To me it seems that this is wrong?

**Comment by aabc** [comment]
Sampling rate is reported in every flow by reference to sampler id (Element 48) or selector id (Element 302), thus collector cannot miss it.

**Comment by tom-x1** [comment]
Thank you for the explanation aabc, very much appreciated. 

I just checked that in my data and you are right. But I'm a little bit confused why is it done this way? Wouldn't it be easier, to report sampling options with each template? Why are there different template types?

**Comment by aabc** [comment]
Because template defines data format, and template says there is 'sampler id' field for a flow, so it's described in template.

**Comment by tom-x1** [comment]
Thank you!
