### ISSUE TITLE
Not getting flows for both ways

### ISSUE THREAD

**Issue by natemccallum** [aabc/ipt-netflow#188]
I'm getting some odd behavior at times. I expect to see 2 flows one for "src" to "dst" and another for the reverse. I'm testing with a simple ssh connection. Sometimes I see both flows and sometimes I only see one direction. I've added rules in iptables for all Chains to use NETFLOW. Do I have something configured incorrectly?

The interesting thing is I see both flows in `/proc/net/stat/ipt_netflow_flows` but for some reason they don't get sent off to the netflow collector.

```
# hash a dev:i,o proto src:ip,port dst:ip,port nexthop tos,tcpflags,options,tcpoptions packets bytes ts:first,last
2 64465 0 11,2 6 172.25.0.2,22 X.X.X.X,56299 10.0.2.1 0,18,0,81000000 10 1160 984,743
...
5 42ff1 0 2,11 6 X.X.X.X,56299 172.25.0.2,22 0.0.0.0 0,18,0,81000000 8 928 995,741
```

__MY SETTINGS__
net.netflow.active_timeout = 1800
net.netflow.debug = 1
net.netflow.destination = 127.0.0.1:2055
net.netflow.flush = 0
net.netflow.hashsize = 655360
net.netflow.inactive_timeout = 15
net.netflow.maxflows = 2000000
net.netflow.protocol = 9
net.netflow.refresh-rate = 20
net.netflow.scan-min = 1
net.netflow.sndbuf = 212992
net.netflow.timeout-rate = 30

**Comment by aabc** [comment]
1. Check for send errors in dmesg.
2. If collector is far away UDP packets may be lost. For the best results keep collector in 1 hop distance.
3. Also, flows does not get sent immediately, there are timeouts. For example you have `active_timeout = 1800`.
