### ISSUE TITLE
issue in kernelr 5.16.11

### ISSUE THREAD

**Issue by kalamlacki** [aabc/ipt-netflow#193]
Hi!

I get:

BUG: using smp_processor_id() in preemptible [00000000] code: sysctl/1311
[   20.078493] caller is netflow_scan_and_export+0x268/0x690 [ipt_NETFLOW]
[   20.078502] CPU: 0 PID: 1311 Comm: sysctl Tainted: G           OE     5.16.11 #1
[   20.078505] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./D1800B-ITX, BIOS P2.10 03/01/2018
[   20.078507] Call Trace:
[   20.078509]  <TASK>
[   20.078511]  dump_stack_lvl+0x48/0x5e
[   20.078516]  check_preemption_disabled+0xde/0xe0
[   20.078521]  netflow_scan_and_export+0x268/0x690 [ipt_NETFLOW]
[   20.078532]  protocol_procctl.cold.49+0x2e/0x4f [ipt_NETFLOW]
[   20.078541]  ? netflow_scan_and_export+0x690/0x690 [ipt_NETFLOW]
[   20.078549]  proc_sys_call_handler+0x1b7/0x2c0
[   20.078554]  new_sync_write+0x11f/0x1b0
[   20.078561]  vfs_write+0x20d/0x2a0
[   20.078566]  ksys_write+0x5f/0xe0
[   20.078571]  do_syscall_64+0x3b/0xc0
[   20.078575]  entry_SYSCALL_64_after_hwframe+0x44/0xae
[   20.078579] RIP: 0033:0x7fc6700d0504
[   20.078583] Code: 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b3 0f 1f 80 00 00 00 00 48 8d 05 f9 61 0d 00 8b 00 85 c0 75 13 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 54 c3 0f 1f 00 41 54 49 89 d4 55 48 89 f5 53
[   20.078586] RSP: 002b:00007ffed74abdf8 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[   20.078590] RAX: ffffffffffffffda RBX: 000055d22caa2560 RCX: 00007fc6700d0504
[   20.078592] RDX: 0000000000000003 RSI: 000055d22caa48f0 RDI: 0000000000000003
[   20.078595] RBP: 000055d22caa6900 R08: 00007fc66fd8b7c0 R09: 00007fc66fd8b7c0
[   20.078597] R10: 000055d22caa2010 R11: 0000000000000246 R12: 00007fc67019d8e0
[   20.078599] R13: 0000000000000003 R14: 00007fc67019d760 R15: 0000000000000003
[   20.078604]  </TASK>
[   20.078607] BUG: using smp_processor_id() in preemptible [00000000] code: sysctl/1311
[   20.078713] caller is netflow_scan_and_export+0x24b/0x690 [ipt_NETFLOW]
[   20.078724] CPU: 0 PID: 1311 Comm: sysctl Tainted: G           OE     5.16.11 #1
[   20.078728] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./D1800B-ITX, BIOS P2.10 03/01/2018
[   20.078730] Call Trace:
[   20.078732]  <TASK>
[   20.078735]  dump_stack_lvl+0x48/0x5e
[   20.078740]  check_preemption_disabled+0xde/0xe0
[   20.078746]  netflow_scan_and_export+0x24b/0x690 [ipt_NETFLOW]
[   20.078756]  protocol_procctl.cold.49+0x2e/0x4f [ipt_NETFLOW]
[   20.078766]  ? netflow_scan_and_export+0x690/0x690 [ipt_NETFLOW]
[   20.078774]  proc_sys_call_handler+0x1b7/0x2c0
[   20.078779]  new_sync_write+0x11f/0x1b0
[   20.078786]  vfs_write+0x20d/0x2a0
[   20.078791]  ksys_write+0x5f/0xe0
[   20.078796]  do_syscall_64+0x3b/0xc0
[   20.078800]  entry_SYSCALL_64_after_hwframe+0x44/0xae
[   20.078805] RIP: 0033:0x7fc6700d0504
[   20.078808] Code: 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b3 0f 1f 80 00 00 00 00 48 8d 05 f9 61 0d 00 8b 00 85 c0 75 13 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 54 c3 0f 1f 00 41 54 49 89 d4 55 48 89 f5 53
[   20.078812] RSP: 002b:00007ffed74abdf8 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[   20.078816] RAX: ffffffffffffffda RBX: 000055d22caa2560 RCX: 00007fc6700d0504
[   20.078818] RDX: 0000000000000003 RSI: 000055d22caa48f0 RDI: 0000000000000003
[   20.078821] RBP: 000055d22caa6900 R08: 00007fc66fd8b7c0 R09: 00007fc66fd8b7c0
[   20.078823] R10: 000055d22caa2010 R11: 0000000000000246 R12: 00007fc67019d8e0
[   20.078825] R13: 0000000000000003 R14: 00007fc67019d760 R15: 0000000000000003
[   20.078830]  </TASK>
[   20.078832] BUG: using smp_processor_id() in preemptible [00000000] code: sysctl/1311
[   20.078901] caller is netflow_scan_and_export+0x268/0x690 [ipt_NETFLOW]
[   20.078910] CPU: 0 PID: 1311 Comm: sysctl Tainted: G           OE     5.16.11 #1
[   20.078914] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./D1800B-ITX, BIOS P2.10 03/01/2018
[   20.078915] Call Trace:
[   20.078917]  <TASK>
[   20.078919]  dump_stack_lvl+0x48/0x5e
[   20.078925]  check_preemption_disabled+0xde/0xe0
[   20.078930]  netflow_scan_and_export+0x268/0x690 [ipt_NETFLOW]
[   20.078940]  protocol_procctl.cold.49+0x2e/0x4f [ipt_NETFLOW]
[   20.078950]  ? netflow_scan_and_export+0x690/0x690 [ipt_NETFLOW]
[   20.078958]  proc_sys_call_handler+0x1b7/0x2c0
[   20.078963]  new_sync_write+0x11f/0x1b0
[   20.078969]  vfs_write+0x20d/0x2a0
[   20.078974]  ksys_write+0x5f/0xe0
[   20.078979]  do_syscall_64+0x3b/0xc0
[   20.078983]  entry_SYSCALL_64_after_hwframe+0x44/0xae
[   20.078988] RIP: 0033:0x7fc6700d0504
[   20.078991] Code: 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b3 0f 1f 80 00 00 00 00 48 8d 05 f9 61 0d 00 8b 00 85 c0 75 13 b8 01 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 54 c3 0f 1f 00 41 54 49 89 d4 55 48 89 f5 53
[   20.078994] RSP: 002b:00007ffed74abdf8 EFLAGS: 00000246 ORIG_RAX: 0000000000000001
[   20.078999] RAX: ffffffffffffffda RBX: 000055d22caa2560 RCX: 00007fc6700d0504
[   20.079001] RDX: 0000000000000003 RSI: 000055d22caa48f0 RDI: 0000000000000003
[   20.079003] RBP: 000055d22caa6900 R08: 00007fc66fd8b7c0 R09: 00007fc66fd8b7c0
[   20.079006] R10: 000055d22caa2010 R11: 0000000000000246 R12: 00007fc67019d8e0
[   20.079008] R13: 0000000000000003 R14: 00007fc67019d760 R15: 0000000000000003
[   20.079013]  </TASK>
[   20.081003] ipt_NETFLOW protocol version 10 (IPFIX) enabled.

on KERNEL 5.16.11

Best regards,
Łukasz

**Comment by kalamlacki** [comment]
https://www.kernel.org/doc/html/latest/locking/preempt-locking.html

**Comment by vvfedorenko** [comment]
Looks like you have CONFIG_DEBUG_PREEMPT in your kernel config. It's not a good idea to have it production environment.
But anyway, I will propose PR to fix the issue

**Comment by aabc** [comment]
Thanks for the repost. Proposed fix is merged too.
