### ISSUE TITLE
"enable-natevents" is not working on Rocky Linux 8.5

### ISSUE THREAD

**Issue by cl-chang** [aabc/ipt-netflow#198]
Hello, I got some error message when I am trying to "make all install".
After I removed the string "const " in ipt_NETFLOW.c:4600, then I can finish the install.
I am not a programmer, will it work fine after I modify it ?

The configure and make steps are shown below.

`# ./configure --enable-natevents --disable-snmp-agent --enable-macaddress --disable-dkms
Module version: 2.6-7-g6a55739
Kernel version: 4.18.0-348.20.1.el8_5.x86_64 (uname)
Kernel sources: /lib/modules/4.18.0-348.20.1.el8_5.x86_64/build (found)
Checking for presence of include/linux/netfilter.h... Yes
netfilter.h uses CONFIG_NF_NAT_NEEDED... Yes
Checking for presence of include/linux/llist.h... Yes
Checking for presence of include/linux/grsecurity.h... No
Iptables binary version: 1.8.4 (nf_tables) (detected from /usr/sbin/iptables)
pkg-config for version 1.8.4 (nf_tables) exists: No (reported: 1.8.4)
Check for working gcc: Yes (gcc)
Checking for presence of xtables.h... Yes
Searching for iptables-1.8.4 (nf_tables) sources..
! Can not find iptables source directory, you may try setting it with --ipt-src=
! This is not fatal error, yet. Will be just using default include dir.
Iptables include flags: none (default)
Iptables module path: /usr/lib64/xtables (from libxtables.so, from binary)
Creating Makefile.. done.

  If you need some options enabled run ./configure --help
  Now run: make all install

**#** make all install
./gen_compat_def > compat_def.h-
Test function xt_family linux/netfilter_ipv4/ip_tables.h  declared
Test struct timeval linux/ktime.h  declared
Test struct proc_ops linux/proc_fs.h  undeclared
Test function synchronize_sched linux/rcupdate.h  undeclared
Test function nf_bridge_info_get linux/netfilter_bridge.h  declared
Test struct vlan_dev_priv linux/if_vlan.h  declared
Test function put_unaligned_be24 asm/unaligned.h  declared
Test function totalram_pages linux/mm.h  declared
Test symbol totalram_pages linux/mm.h  declared
Test member nf_ct_event_notifier.ct_event net/netfilter/nf_conntrack_ecache.h  undeclared
mv compat_def.h- compat_def.h
Compiling 2.6-7-g6a55739 for kernel 4.18.0-348.20.1.el8_5.x86_64
make -C /lib/modules/4.18.0-348.20.1.el8_5.x86_64/build M=/root/ipt-netflow modules
make[1]: Entering directory '/usr/src/kernels/4.18.0-348.20.1.el8_5.x86_64'
  CC [M]  /root/ipt-netflow/ipt_NETFLOW.o
/root/ipt-netflow/ipt_NETFLOW.c: In function ‘netflow_conntrack_event’:
/root/ipt-netflow/ipt_NETFLOW.c:4622:36: warning: passing argument 2 of ‘notifier->fcn’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   ret = notifier->ct_event(events, item);
                                    ^~~~
/root/ipt-netflow/ipt_NETFLOW.c:4622:36: note: expected ‘struct nf_ct_event *’ but argument is of type ‘const struct nf_ct_event *’
/root/ipt-netflow/ipt_NETFLOW.c: At top level:
/root/ipt-netflow/ipt_NETFLOW.c:4687:14: error: initialization of ‘int (*)(unsigned int,  struct nf_ct_event *)’ from incompatible pointer type ‘int (*)(const unsigned int,  const struct nf_ct_event *)’ [-Werror=incompatible-pointer-types]
  .ct_event = netflow_conntrack_event
              ^~~~~~~~~~~~~~~~~~~~~~~
/root/ipt-netflow/ipt_NETFLOW.c:4687:14: note: (near initialization for ‘ctnl_notifier.fcn’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:322: /root/ipt-netflow/ipt_NETFLOW.o] Error 1
make[1]: *** [Makefile:1571: _module_/root/ipt-netflow] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.18.0-348.20.1.el8_5.x86_64'
make: *** [Makefile:27: ipt_NETFLOW.ko] Error 2`

**Comment by aabc** [comment]
Thanks for the report! Should be fixed in git `master`.
