### ISSUE TITLE
Compile error on kernel 4.15.0, Ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by scamp** [aabc/ipt-netflow#206]
DKMS make.log for ipt-netflow-2.6-12-g40fefb2 for kernel 4.15.0-194-generic (x86_64)
Fri Dec  9 23:38:42 EET 2022
./gen_compat_def > compat_def.h-
Test function xt_family linux/netfilter_ipv4/ip_tables.h  declared
Test struct timeval linux/ktime.h  declared
Test struct proc_ops linux/proc_fs.h  undeclared
Test function synchronize_sched linux/rcupdate.h  declared
Test function nf_bridge_info_get linux/netfilter_bridge.h  undeclared
Test struct vlan_dev_priv linux/if_vlan.h  declared
Test function put_unaligned_be24 asm/unaligned.h  undeclared
Test function totalram_pages linux/mm.h  undeclared
Test symbol totalram_pages linux/mm.h  declared
Test member nf_ct_event_notifier.ct_event net/netfilter/nf_conntrack_ecache.h  undeclared
mv compat_def.h- compat_def.h
Compiling 2.6 for kernel 4.15.0-194-generic
make -C /lib/modules/4.15.0-194-generic/build M=/var/lib/dkms/ipt-netflow/2.6-12-g40fefb2/build modules
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-194-generic'
  CC [M]  /var/lib/dkms/ipt-netflow/2.6-12-g40fefb2/build/ipt_NETFLOW.o
/var/lib/dkms/ipt-netflow/2.6-12-g40fefb2/build/ipt_NETFLOW.c: In function ‘netflow_work_fn’:
/var/lib/dkms/ipt-netflow/2.6-12-g40fefb2/build/ipt_NETFLOW.c:4504:11: error: implicit declaration of function ‘__smp_processor_id’; did you mean ‘smp_processor_id’? [-Werror=implicit-function-declaration]
  wk_cpu = __smp_processor_id();
           ^~~~~~~~~~~~~~~~~~
           smp_processor_id
cc1: some warnings being treated as errors
scripts/Makefile.build:340: recipe for target '/var/lib/dkms/ipt-netflow/2.6-12-g40fefb2/build/ipt_NETFLOW.o' failed
make[2]: *** [/var/lib/dkms/ipt-netflow/2.6-12-g40fefb2/build/ipt_NETFLOW.o] Error 1
Makefile:1590: recipe for target '_module_/var/lib/dkms/ipt-netflow/2.6-12-g40fefb2/build' failed
make[1]: *** [_module_/var/lib/dkms/ipt-netflow/2.6-12-g40fefb2/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-194-generic'
Makefile:26: recipe for target 'ipt_NETFLOW.ko' failed
make: *** [ipt_NETFLOW.ko] Error 2

**Comment by kalamlacki** [comment]
If you use older version of the module you will not get this error

**Comment by prometheus84** [comment]
Hi,

can you share the older version of the module, as i am not able to find.

**Comment by scamp** [comment]
[v2.5.1](https://github.com/aabc/ipt-netflow/tree/v2.5.1) is bulding with no issues.
