### ISSUE TITLE
wk_cpu = __smp_processor_id(); 

### ISSUE THREAD

**Issue by prometheus84** [aabc/ipt-netflow#207]
Not able to compile due to "wk_cpu = __smp_processor_id();", pls suggest, Kernel version: 4.15.0-200-generic (uname)

Compiling 2.6-12-g40fefb2 for kernel 4.15.0-200-generic
make -C /lib/modules/4.15.0-200-generic/build M=/root/ipt-netflow modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-200-generic'
  CC [M]  /root/ipt-netflow/ipt_NETFLOW.o
/root/ipt-netflow/ipt_NETFLOW.c: In function ‘netflow_work_fn’:
/root/ipt-netflow/ipt_NETFLOW.c:4504:11: error: implicit declaration of function ‘__smp_processor_id’; did you mean ‘smp_processor_id’? [-Werror=implicit-function-declaration]
  wk_cpu = __smp_processor_id();
           ^~~~~~~~~~~~~~~~~~
           smp_processor_id
cc1: some warnings being treated as errors
scripts/Makefile.build:340: recipe for target '/root/ipt-netflow/ipt_NETFLOW.o' failed
make[2]: *** [/root/ipt-netflow/ipt_NETFLOW.o] Error 1
Makefile:1594: recipe for target '_module_/root/ipt-netflow' failed
make[1]: *** [_module_/root/ipt-netflow] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-200-generic'
Makefile:26: recipe for target 'ipt_NETFLOW.ko' failed
make: *** [ipt_NETFLOW.ko] Error 2

**Comment by kalamlacki** [comment]
please move to previous version by:
git checkout tags/v2.5.1 and it will work fine

**Comment by prometheus84** [comment]
error: pathspec 'tags/v2.5.1' did not match any file(s) known to git

**Comment by kalamlacki** [comment]
git clone https://github.com/aabc/ipt-netflow.git
cd ipt-netflow
git checkout tags/v2.5.1 

This works fine

**Comment by prometheus84** [comment]
Thank you it worked, i am seeing the stats table with data. But i am unable to send nat logs to remote host with netflow9/ipfix installed.

root@maxnet:~/ipt-netflow# cat /proc/net/stat/ipt_netflow
ipt_NETFLOW 2.5.1, srcversion 002230B6D1795B7F765D38C; llist
Protocol version 9 (netflow), refresh-rate 20, timeout-rate 30, (templates 6, active 6).
Timeouts: active 1800s, inactive 15s. Maxflows 2000000
Flows: active 76 (peak 266 reached 0d0h21m ago), mem 266K, worker delay 25/250 [1..25] (60 ms, 0 us, 65:0 0 [cpu4]).
Hash: size 32768 (mem 256K), metric 1.00 [1.00, 1.00, 1.00]. InHash: 503 pkt, 128 K, InPDU 64, 3588.
Rate: 8016 bits/sec, 12 packets/sec; Avg 1 min: 23863 bps, 12 pps; 5 min: 15787 bps, 2 pps
cpu#     pps; <search found new [metric], trunc frag alloc maxflows>, traffic: <pkt, bytes>, drop: <pkt, bytes>
Total     10;    126 543757 253021 [1.00],    0    0    0    0, traffic: 796778, 97 MB, drop: 0, 0 K
cpu0       0;      8  27690  16735 [1.00],    0    0    0    0, traffic: 44425, 4 MB, drop: 0, 0 K
cpu1       0;      0    865     73 [1.00],    0    0    0    0, traffic: 938, 0 MB, drop: 0, 0 K
cpu2       1;      2  54569  18401 [1.00],    0    0    0    0, traffic: 72970, 6 MB, drop: 0, 0 K
cpu3       0;     15  17859   9433 [1.00],    0    0    0    0, traffic: 27292, 2 MB, drop: 0, 0 K
cpu4       0;      5  46796  13362 [1.00],    0    0    0    0, traffic: 60158, 32 MB, drop: 0, 0 K
cpu5       1;     36  24459  14472 [1.00],    0    0    0    0, traffic: 38931, 4 MB, drop: 0, 0 K
cpu6       0;      0  31821  17653 [1.00],    0    0    0    0, traffic: 49474, 3 MB, drop: 0, 0 K
cpu7       1;     17  52508  23395 [1.00],    0    0    0    0, traffic: 75903, 6 MB, drop: 0, 0 K
cpu8       1;     22  41387  19849 [1.00],    0    0    0    0, traffic: 61236, 4 MB, drop: 0, 0 K
cpu9       1;      1  31825  11623 [1.00],    0    0    0    0, traffic: 43448, 3 MB, drop: 0, 0 K
cpu10      1;      4  39517  15100 [1.00],    0    0    0    0, traffic: 54617, 4 MB, drop: 0, 0 K
cpu11      1;      8  45946  37297 [1.00],    0    0    0    0, traffic: 83243, 7 MB, drop: 0, 0 K
cpu12      0;      0  16856   5918 [1.00],    0    0    0    0, traffic: 22774, 3 MB, drop: 0, 0 K
cpu13      1;      1  38807  16858 [1.00],    0    0    0    0, traffic: 55665, 5 MB, drop: 0, 0 K
cpu14      1;      3  24850  14847 [1.00],    0    0    0    0, traffic: 39697, 3 MB, drop: 0, 0 K
cpu15      1;      4  48002  18005 [1.00],    0    0    0    0, traffic: 66007, 5 MB, drop: 0, 0 K
Export: Rate 0 bytes/s; Total 7931 pkts, 9 MB, 252911 flows; Errors 0 pkts; Traffic lost 0 pkts, 0 Kbytes, 0 flows.
sock0: 127.0.0.1:2055, sndbuf 212992, filled 1, peak 1; err: sndbuf reached 0, connect 0, cberr 7931, other 0
