### ISSUE TITLE
periodic will reconnect

### ISSUE THREAD

**Issue by manchelsi** [aabc/ipt-netflow#210]
Периодически вываливается:

kernel: ipt_NETFLOW: sendmsg[1] error -22: data loss 827 pkt, 1064025 bytes: will reconnect.
kernel: ipt_NETFLOW: connected <My IP>

**Comment by svlobanov** [comment]
try to increase sndbuf

**Comment by manchelsi** [comment]
it looks like when installed on debian iptables-netflow-dkms, it is built with nf_conntrack, and run with this module

**Comment by manchelsi** [comment]
it didn't help, disabled conntrack, increased sndbuf

**Comment by manchelsi** [comment]
sndbuf 33554432. Does not help.

**Comment by manchelsi** [comment]
The remote side does not always send a response.
Is it possible to disable the connection check?
