### ISSUE TITLE
EINVAL when interface state changes

### ISSUE THREAD

**Issue by commonism** [aabc/ipt-netflow#26]
Hi,

I got a problem running ipt_NETFLOW in a active/backup failover setup.
During failover, interfaces change, so the interface ipt_NETFLOW used to send flows will get unavailable.
ipt_NETFLOW does not recover from this situation, and keeps logging:

```
kernel: [232283.590800] netflow_sendmsg: sendmsg(0, 1012) [1 229376]
kernel: [232283.590808] ipt_NETFLOW: sendmsg[0] error -22: data loss 0 pkt, 0 bytes
```

-22 is EINVAL.
I'd propose to disconnect the socket on EINVAL during sendmsg, set -1, and it will reconnect later on.

**Comment by aabc** [comment]
What version of ipt-netflow you are using?

**Comment by commonism** [comment]
modinfo -F version ipt_NETFLOW
2.0-60-ga035a43

was build at ~20141208

**Comment by aabc** [comment]
Thanks. I will look into issue later today. Probably will accept your sugegstion.

**Comment by aabc** [comment]
Commited fix 4e70423. But this is untested (even though looked simple enough to be fail proof), as fault situation is a bit complicated. If you can, please test and report.

**Comment by commonism** [comment]
tested, works as advertised.

Thanks.

**Comment by aabc** [comment]
Thank you!
