### ISSUE TITLE
compilation errors on kernel 4.2.3

### ISSUE THREAD

**Issue by nuqleo** [aabc/ipt-netflow#46]
There are module ipt_NETFLOW.ko compilation errors for kernel 4.2.3-300.fc23.x86_64 with options --enable-vlan

Compiling for kernel 4.2.3-300.fc23.x86_64
make -C /lib/modules/4.2.3-300.fc23.x86_64/build M=/var/lib/dkms/ipt-netflow/2.1-1.fc23/build modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory '/usr/src/kernels/4.2.3-300.fc23.x86_64'
  CC [M]  /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.o
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c: In function 'parse_l2_header':
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:4677:6: error: implicit declaration of function 'vlan_tx_tag_present' [-Werror=implicit-function-declaration]
  if (vlan_tx_tag_present(skb))
      ^
In file included from include/linux/swab.h:4:0,
                 from include/uapi/linux/byteorder/little_endian.h:12,
                 from include/linux/byteorder/little_endian.h:4,
                 from ./arch/x86/include/uapi/asm/byteorder.h:4,
                 from include/asm-generic/bitops/le.h:5,
                 from ./arch/x86/include/asm/bitops.h:504,
                 from include/linux/bitops.h:36,
                 from include/linux/kernel.h:10,
                 from include/linux/list.h:8,
                 from include/linux/module.h:9,
                 from /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:21:
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:4678:33: error: implicit declaration of function 'vlan_tx_tag_get' [-Werror=implicit-function-declaration]
   tuple->tag[tag_num++] = htons(vlan_tx_tag_get(skb));
                                 ^
include/uapi/linux/swab.h:106:32: note: in definition of macro '__swab16'
  (__builtin_constant_p((__u16)(x)) ? \
                                ^
include/linux/byteorder/generic.h:134:21: note: in expansion of macro '__cpu_to_be16'
 #define ___htons(x) __cpu_to_be16(x)
                     ^
include/linux/byteorder/generic.h:140:18: note: in expansion of macro '___htons'
 #define htons(x) ___htons(x)
                  ^
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:4678:27: note: in expansion of macro 'htons'
   tuple->tag[tag_num++] = htons(vlan_tx_tag_get(skb));
                           ^
cc1: some warnings being treated as errors
scripts/Makefile.build:264: recipe for target '/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.o' failed
make[2]: *** [/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.o] Error 1
Makefile:1390: recipe for target '_module_/var/lib/dkms/ipt-netflow/2.1-1.fc23/build' failed
make[1]: *** [_module_/var/lib/dkms/ipt-netflow/2.1-1.fc23/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.2.3-300.fc23.x86_64'
Makefile:24: recipe for target 'ipt_NETFLOW.ko' failed
make: *** [ipt_NETFLOW.ko] Error 2

And with option --enable-promisc

Compiling for kernel 4.2.3-300.fc23.x86_64
make -C /lib/modules/4.2.3-300.fc23.x86_64/build M=/var/lib/dkms/ipt-netflow/2.1-1.fc23/build modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory '/usr/src/kernels/4.2.3-300.fc23.x86_64'
  CC [M]  /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.o
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c: In function 'promisc4_rcv':
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:1211:52: warning: passing argument 3 of 'NF_HOOK' from incompatible pointer type [-Wincompatible-pointer-types]
  return NF_HOOK(NFPROTO_IPV4, NF_INET_PRE_ROUTING, skb, dev, NULL, promisc_finish);
                                                    ^
In file included from include/uapi/linux/netfilter_ipv4.h:8:0,
                 from include/linux/netfilter_ipv4.h:7,
                 from include/uapi/linux/netfilter_ipv4/ip_tables.h:20,
                 from include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:52:
include/linux/netfilter.h:236:1: note: expected 'struct sock *' but argument is of type 'struct sk_buff *'
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:1211:57: warning: passing argument 4 of 'NF_HOOK' from incompatible pointer type [-Wincompatible-pointer-types]
  return NF_HOOK(NFPROTO_IPV4, NF_INET_PRE_ROUTING, skb, dev, NULL, promisc_finish);
                                                         ^
In file included from include/uapi/linux/netfilter_ipv4.h:8:0,
                 from include/linux/netfilter_ipv4.h:7,
                 from include/uapi/linux/netfilter_ipv4/ip_tables.h:20,
                 from include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:52:
include/linux/netfilter.h:236:1: note: expected 'struct sk_buff *' but argument is of type 'struct net_device *'
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:1211:68: warning: passing argument 6 of 'NF_HOOK' from incompatible pointer type [-Wincompatible-pointer-types]
  return NF_HOOK(NFPROTO_IPV4, NF_INET_PRE_ROUTING, skb, dev, NULL, promisc_finish);
                                                                    ^
In file included from include/uapi/linux/netfilter_ipv4.h:8:0,
                 from include/linux/netfilter_ipv4.h:7,
                 from include/uapi/linux/netfilter_ipv4/ip_tables.h:20,
                 from include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:52:
include/linux/netfilter.h:236:1: note: expected 'struct net_device *' but argument is of type 'int (*)(struct sk_buff *)'
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:1211:9: error: too few arguments to function 'NF_HOOK'
  return NF_HOOK(NFPROTO_IPV4, NF_INET_PRE_ROUTING, skb, dev, NULL, promisc_finish);
         ^
In file included from include/uapi/linux/netfilter_ipv4.h:8:0,
                 from include/linux/netfilter_ipv4.h:7,
                 from include/uapi/linux/netfilter_ipv4/ip_tables.h:20,
                 from include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:52:
include/linux/netfilter.h:236:1: note: declared here
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c: In function 'promisc6_rcv':
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:1279:52: warning: passing argument 3 of 'NF_HOOK' from incompatible pointer type [-Wincompatible-pointer-types]
  return NF_HOOK(NFPROTO_IPV6, NF_INET_PRE_ROUTING, skb, dev, NULL, promisc_finish);
                                                    ^
In file included from include/uapi/linux/netfilter_ipv4.h:8:0,
                 from include/linux/netfilter_ipv4.h:7,
                 from include/uapi/linux/netfilter_ipv4/ip_tables.h:20,
                 from include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:52:
include/linux/netfilter.h:236:1: note: expected 'struct sock *' but argument is of type 'struct sk_buff *'
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:1279:57: warning: passing argument 4 of 'NF_HOOK' from incompatible pointer type [-Wincompatible-pointer-types]
  return NF_HOOK(NFPROTO_IPV6, NF_INET_PRE_ROUTING, skb, dev, NULL, promisc_finish);
                                                         ^
In file included from include/uapi/linux/netfilter_ipv4.h:8:0,
                 from include/linux/netfilter_ipv4.h:7,
                 from include/uapi/linux/netfilter_ipv4/ip_tables.h:20,
                 from include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:52:
include/linux/netfilter.h:236:1: note: expected 'struct sk_buff *' but argument is of type 'struct net_device *'
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:1279:68: warning: passing argument 6 of 'NF_HOOK' from incompatible pointer type [-Wincompatible-pointer-types]
  return NF_HOOK(NFPROTO_IPV6, NF_INET_PRE_ROUTING, skb, dev, NULL, promisc_finish);
                                                                    ^
In file included from include/uapi/linux/netfilter_ipv4.h:8:0,
                 from include/linux/netfilter_ipv4.h:7,
                 from include/uapi/linux/netfilter_ipv4/ip_tables.h:20,
                 from include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:52:
include/linux/netfilter.h:236:1: note: expected 'struct net_device *' but argument is of type 'int (*)(struct sk_buff *)'
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:1279:9: error: too few arguments to function 'NF_HOOK'
  return NF_HOOK(NFPROTO_IPV6, NF_INET_PRE_ROUTING, skb, dev, NULL, promisc_finish);
         ^
In file included from include/uapi/linux/netfilter_ipv4.h:8:0,
                 from include/linux/netfilter_ipv4.h:7,
                 from include/uapi/linux/netfilter_ipv4/ip_tables.h:20,
                 from include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.c:52:
include/linux/netfilter.h:236:1: note: declared here
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
scripts/Makefile.build:264: recipe for target '/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.o' failed
make[2]: *** [/var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.o] Error 1
Makefile:1390: recipe for target '_module_/var/lib/dkms/ipt-netflow/2.1-1.fc23/build' failed
make[1]: *** [_module_/var/lib/dkms/ipt-netflow/2.1-1.fc23/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.2.3-300.fc23.x86_64'
Makefile:24: recipe for target 'ipt_NETFLOW.ko' failed
make: *** [ipt_NETFLOW.ko] Error 2

Module compiles fine if only options --enable-macaddress and --enable-direction added

Compiling for kernel 4.2.3-300.fc23.x86_64
make -C /lib/modules/4.2.3-300.fc23.x86_64/build M=/var/lib/dkms/ipt-netflow/2.1-1.fc23/build modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory '/usr/src/kernels/4.2.3-300.fc23.x86_64'
  CC [M]  /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.mod.o
  LD [M]  /var/lib/dkms/ipt-netflow/2.1-1.fc23/build/ipt_NETFLOW.ko
make[1]: Leaving directory '/usr/src/kernels/4.2.3-300.fc23.x86_64'

ipt-netflow git snapshot from 2015-11-01 used.

**Comment by aabc** [comment]
The issue should be resolved now. Thanks for reporting!

**Comment by nuqleo** [comment]
Compiled fine also for 4.3.0 kernel. Thanks.

**Comment by aabc** [comment]
Yes, I tested compilation on 4.3 too, with all `configure` options.
