### ISSUE TITLE
Compile error on CentOS 7.1 3.10.0-327.4.4.el7.x86_64

### ISSUE THREAD

**Issue by mzi77** [aabc/ipt-netflow#52]
Hi,

I have HEAD compile problems on 3.10.0-327.4.4.el7.x86_64
with

./configure --enable-promisc --enable-vlan --promisc-mpls

`
[root@eth0 20160118-ipt-netflow]# make
Compiling for kernel 3.10.0-327.4.4.el7.x86_64
make -C /lib/modules/3.10.0-327.4.4.el7.x86_64/build M=/root/ipt-netflow/20160118-ipt-netflow modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory `/usr/src/kernels/3.10.0-327.4.4.el7.x86_64'
  CC [M]  /root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.o
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c: In function ‘promisc4_rcv’:
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:1215:2: warning: passing argument 3 of ‘NF_HOOK’ from incompatible pointer type [enabled by default]
  return NF_HOOK_COMPAT(NFPROTO_IPV4, NF_INET_PRE_ROUTING, NULL,
  ^
In file included from include/net/netns/netfilter.h:5:0,
                 from include/net/net_namespace.h:21,
                 from include/linux/netdevice.h:43,
                 from include/net/inet_sock.h:24,
                 from include/linux/udp.h:20,
                 from /root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:32:
include/linux/netfilter.h:245:1: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:1215:2: warning: passing argument 4 of ‘NF_HOOK’ from incompatible pointer type [enabled by default]
  return NF_HOOK_COMPAT(NFPROTO_IPV4, NF_INET_PRE_ROUTING, NULL,
  ^
In file included from include/net/netns/netfilter.h:5:0,
                 from include/net/net_namespace.h:21,
                 from include/linux/netdevice.h:43,
                 from include/net/inet_sock.h:24,
                 from include/linux/udp.h:20,
                 from /root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:32:
include/linux/netfilter.h:245:1: note: expected ‘struct sk_buff *’ but argument is of type ‘struct net_device *’
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:1215:2: warning: passing argument 6 of ‘NF_HOOK’ from incompatible pointer type [enabled by default]
  return NF_HOOK_COMPAT(NFPROTO_IPV4, NF_INET_PRE_ROUTING, NULL,
  ^
In file included from include/net/netns/netfilter.h:5:0,
                 from include/net/net_namespace.h:21,
                 from include/linux/netdevice.h:43,
                 from include/net/inet_sock.h:24,
                 from include/linux/udp.h:20,
                 from /root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:32:
include/linux/netfilter.h:245:1: note: expected ‘struct net_device *’ but argument is of type ‘int (*)(struct sk_buff *)’
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:1215:2: error: too few arguments to function ‘NF_HOOK’
  return NF_HOOK_COMPAT(NFPROTO_IPV4, NF_INET_PRE_ROUTING, NULL,
  ^
In file included from include/net/netns/netfilter.h:5:0,
                 from include/net/net_namespace.h:21,
                 from include/linux/netdevice.h:43,
                 from include/net/inet_sock.h:24,
                 from include/linux/udp.h:20,
                 from /root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:32:
include/linux/netfilter.h:245:1: note: declared here
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c: In function ‘promisc6_rcv’:
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:1284:2: warning: passing argument 3 of ‘NF_HOOK’ from incompatible pointer type [enabled by default]
  return NF_HOOK_COMPAT(NFPROTO_IPV6, NF_INET_PRE_ROUTING, NULL,
  ^
In file included from include/net/netns/netfilter.h:5:0,
                 from include/net/net_namespace.h:21,
                 from include/linux/netdevice.h:43,
                 from include/net/inet_sock.h:24,
                 from include/linux/udp.h:20,
                 from /root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:32:
include/linux/netfilter.h:245:1: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:1284:2: warning: passing argument 4 of ‘NF_HOOK’ from incompatible pointer type [enabled by default]
  return NF_HOOK_COMPAT(NFPROTO_IPV6, NF_INET_PRE_ROUTING, NULL,
  ^
In file included from include/net/netns/netfilter.h:5:0,
                 from include/net/net_namespace.h:21,
                 from include/linux/netdevice.h:43,
                 from include/net/inet_sock.h:24,
                 from include/linux/udp.h:20,
                 from /root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:32:
include/linux/netfilter.h:245:1: note: expected ‘struct sk_buff *’ but argument is of type ‘struct net_device *’
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:1284:2: warning: passing argument 6 of ‘NF_HOOK’ from incompatible pointer type [enabled by default]
  return NF_HOOK_COMPAT(NFPROTO_IPV6, NF_INET_PRE_ROUTING, NULL,
  ^
In file included from include/net/netns/netfilter.h:5:0,
                 from include/net/net_namespace.h:21,
                 from include/linux/netdevice.h:43,
                 from include/net/inet_sock.h:24,
                 from include/linux/udp.h:20,
                 from /root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:32:
include/linux/netfilter.h:245:1: note: expected ‘struct net_device *’ but argument is of type ‘int (*)(struct sk_buff *)’
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:1284:2: error: too few arguments to function ‘NF_HOOK’
  return NF_HOOK_COMPAT(NFPROTO_IPV6, NF_INET_PRE_ROUTING, NULL,
  ^
In file included from include/net/netns/netfilter.h:5:0,
                 from include/net/net_namespace.h:21,
                 from include/linux/netdevice.h:43,
                 from include/net/inet_sock.h:24,
                 from include/linux/udp.h:20,
                 from /root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.c:32:
include/linux/netfilter.h:245:1: note: declared here
 NF_HOOK(uint8_t pf, unsigned int hook, struct sock *sk, struct sk_buff *skb,
 ^
make[2]: *** [/root/ipt-netflow/20160118-ipt-netflow/ipt_NETFLOW.o] Error 1
make[1]: *** [_module_/root/ipt-netflow/20160118-ipt-netflow] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-327.4.4.el7.x86_64'
make: *** [ipt_NETFLOW.ko] Error 2
[root@eth0 20160118-ipt-netflow]# 
`

**Comment by aabc** [comment]
Thanks for the report.

**Comment by mzi77** [comment]
Thank you, I confirm that this issue is fixed.
