### ISSUE TITLE
Iptables headers not found. You may need to specify --ipt-inc=...

### ISSUE THREAD

**Issue by jura22** [aabc/ipt-netflow#64]
Hello.

I cant configure ipt-netflow-2.2 on centos 7.

# uname -a
Linux maticni-gate 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[root@maticni-gate ipt-netflow]# pwd
/usr/local/src/ipt-netflow
[root@maticni-gate ipt-netflow]# ./configure 
Kernel version: 3.10.0-327.36.1.el7.x86_64 (uname)
Kernel sources: /lib/modules/3.10.0-327.36.1.el7.x86_64/build (found)
Checking for presence of include/linux/llist.h... Yes
Checking for presence of include/linux/grsecurity.h... No
Iptables binary version: 1.4.21 (detected from /sbin/iptables)
pkg-config for version 1.4.21 exists: Yes
Checking for presence of xtables.h... No
Checking for presence of iptables.h... No
! Iptables headers not found. You may need to specify --ipt-inc=...
! 
! Under Centos simply run this:
!   root# yum install iptables-devel.x86_64 pkgconfig
[root@maticni-gate ipt-netflow]# rpm -ql iptables-devel
/usr/include/ip6tables.h
/usr/include/iptables
/usr/include/iptables.h
/usr/include/iptables/internal.h
/usr/include/libiptc
/usr/include/libiptc/ipt_kernel_headers.h
/usr/include/libiptc/libip6tc.h
/usr/include/libiptc/libiptc.h
/usr/include/libiptc/libxtc.h
/usr/include/libiptc/xtcshared.h
/usr/include/libipulog
/usr/include/libipulog/libipulog.h
/usr/include/xtables-version.h
/usr/include/xtables.h
/usr/lib64/libip4tc.so
/usr/lib64/libip6tc.so
/usr/lib64/libiptc.so
/usr/lib64/libxtables.so
/usr/lib64/pkgconfig/libip4tc.pc
/usr/lib64/pkgconfig/libip6tc.pc
/usr/lib64/pkgconfig/libiptc.pc
/usr/lib64/pkgconfig/xtables.pc
[root@maticni-gate ipt-netflow]# rpm -ql pkgconfig
/usr/bin/pkg-config
/usr/lib64/pkgconfig
/usr/share/aclocal/pkg.m4
/usr/share/doc/pkgconfig-0.27.1
/usr/share/doc/pkgconfig-0.27.1/AUTHORS
/usr/share/doc/pkgconfig-0.27.1/COPYING
/usr/share/doc/pkgconfig-0.27.1/NEWS
/usr/share/doc/pkgconfig-0.27.1/README
/usr/share/doc/pkgconfig-0.27.1/pkg-config-guide.html
/usr/share/man/man1/pkg-config.1.gz
/usr/share/pkgconfig

[root@maticni-gate ipt-netflow]# ./configure --ipt-inc=/usr/include
Kernel version: 3.10.0-327.36.1.el7.x86_64 (uname)
Kernel sources: /lib/modules/3.10.0-327.36.1.el7.x86_64/build (found)
Checking for presence of include/linux/llist.h... Yes
Checking for presence of include/linux/grsecurity.h... No
Iptables binary version: 1.4.21 (detected from /sbin/iptables)
pkg-config for version 1.4.21 exists: Yes
Checking for presence of xtables.h... No
Checking for presence of iptables.h... No
! Iptables headers not found. You may need to specify --ipt-inc=...
! 
! Under Centos simply run this:
!   root# yum install iptables-devel.x86_64 pkgconfig

Any idea ?

**Comment by aabc** [comment]
Could you do `pkg-config --cflags xtables|od -x` pls?

**Comment by jura22** [comment]
[root@maticni-gate ipt-netflow-2.2]# pkg-config --cflags xtables|od -x
0000000 0a20
0000002

**Comment by aabc** [comment]
Thanks. Could you also show output of:
```
$ ls -l /usr/include/xtables.h
$ echo -e '#define __EXPORTED_HEADERS__\n#include <xtables.h>\n' > test.c
$ gcc -c test.c
```

**Comment by jura22** [comment]
Good job. Its my fault. Missing gcc. Please insert in to README first step for CentOS/RHEL:
`yum group install "Development Tools"`
Thanks

**Comment by aabc** [comment]
Thanks!
