### ISSUE TITLE
Add ability to specify source IP of netflow emissions

### ISSUE THREAD

**Issue by ekgermann** [aabc/ipt-netflow#71]
Currently working with ipt-netflow on a linux based router with multiple interfaces (tunnels, etc).

It seems to randomly pick an interface to be the source interface for packets emitted.  

Since many of the open-source collectors don't have the ability to specify an Engine ID, it would be helpful to have a config option to specify the source IP to be used when sending packets so it was static when interfaces were added or deleted to the linux box.

I've tried adding it myself, but my skills are a bit rusty.

EKG

**Comment by aabc** [comment]
Source should be picked not randomly, but depending on routing, such as primary IP of egress interface.

But, maybe this will be useful feature, I will think about it.

**Comment by aabc** [comment]
I implemented your feature request. Now you are obliged to test it. ;-)

**Comment by aabc** [comment]
@michaeljbailey Thanks much for the testing!

**Comment by michaeljbailey** [comment]
@aabc I may have spoke a bit too soon. I tried testing with a source interface and it did not work for a subinterface:

`net.netflow.destination 172.16.18.13:2055%switch0.410,172.16.18.135:2055%switch0.410`


I no longer see any traffic netflow traffic generated, running either a local tcpdump or a remote tcpdump.

I am going to try testing with a plain interface descriptor (eth0, for example), to see if this might be an issue in the interface name parsing.

**Comment by aabc** [comment]
@michaeljbailey Please check if there is error messages in dmesg.

**Comment by michaeljbailey** [comment]
@aabc No messages in either dmesg or messages (where Ubiquiti typically dumps log messages).

I tested with a legitimate interface name and a dummy interface name. With a dummy interface name, I see the expected error message:

```
sysctl -w net.netflow.destination=172.16.18.13:2055%switch0.410,172.16.18.135:2055%sXZV$#T%

root@Router:~# tail /var/log/messages 
Apr 26 11:03:05 Router kernel: sysctl: The scan_unevictable_pages sysctl/node-interface has been disabled for lack of a legitimate use case.  If you have one, please send an email to linux-mm@kvack.org.
Apr 26 11:06:16 Router radvd[5711]: sendmsg: Operation not permitted
Apr 26 11:07:28  radvd[5711]: last message repeated 2 times
Apr 26 11:08:38 Router radvd[5711]: sendmsg: Operation not permitted
Apr 26 11:12:03 Router radvd[5711]: sendmsg: Operation not permitted
Apr 26 11:14:46 Router radvd[5711]: sendmsg: Operation not permitted
Apr 26 11:16:44 Router radvd[5711]: sendmsg: Operation not permitted
Apr 26 11:16:46 Router radvd[5711]: sendmsg: Operation not permitted
Apr 26 11:17:31 Router kernel: ipt_NETFLOW: error binding to device sXZV1T%, errno 0
Apr 26 11:18:32 Router kernel: last message repeated 8 times```

**Comment by aabc** [comment]
Thanks. That kernel version it is?

**Comment by aabc** [comment]
Btw, does `switch0.410` have routing to the `172.16.18.13`? You may try to check this with something like `ip ro get 172.16.18.13 oif switch0.410`.

**Comment by michaeljbailey** [comment]
Kernel version and route entry below:

```
root@Router:~# uname -a
Linux Router 3.10.107-UBNT #1 SMP Wed Feb 13 20:05:27 UTC 2019 mips GNU/Linux

Router~# ip ro get 172.16.18.13 oif switch0.410
172.16.18.13 dev switch0.410  src 172.16.4.70 
    cache 
```

**Comment by aabc** [comment]
You did not state on what interface you ran tcpdump. So, can you run `tcpdump -n -i switch0.410` and check if there are packets?

**Comment by michaeljbailey** [comment]
Sorry - I was running my tcpdump for the most general way:

`tcpdump -ni any port 2055`

Doesn't seem to be any big difference if I isolate to the specific interface.

**Comment by aabc** [comment]
@michaeljbailey Thanks for the testing. I will need to investigate this further.

**Comment by aabc** [comment]
@michaeljbailey I did some change to the interface binding code. Can you test from the git head?
