### ISSUE TITLE
Netflow packets are sent as protocol 8 instead of 17

### ISSUE THREAD

**Issue by nL1ght5** [aabc/ipt-netflow#76]
Compiled ipt-netflow for Lede 17.01.1 for Archer C7 v2. The module is loading fine and packets are indeed sent out to the destination. However, for some odd  reason the packets are sent as protocol EGP(8) instead of UDP(17).

The actual cflow data inside of the packets seems to be intact as I can load a .pcap into wireshark and see the cflow information after forcing Wireshark to decode it as UDP instead of EGP. 

ipt-netflow versions tested:
-HEAD
-V2.2

Lede information:
Target System (Atheros AR7xxx/AR9xxx)
Target Profile (TP-LINK Archer C7 v2)

Netstat on sending device:
root@LEDE:~# netstat -nu
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
udp        0  65534 10.1.1.130:59091        10.1.1.244:2055         ESTABLISHED

**Comment by aabc** [comment]
Similarly irrational problem is described at https://github.com/aabc/ipt-netflow/issues/72.

Module sends data using usual UDP socket. It does not construct packets manually. So, if there is EGP packets sent out of UDP socket, probably this is not module's fault, but general kernel problem.

**Comment by nL1ght5** [comment]
Issue resolved, to summarize - be sure that the kmod and kernel was built on the same machine.

**Comment by aabc** [comment]
Thanks for informing!
