### ISSUE TITLE
ipt-netflow-2.2 fails to build kernel-ml-4.12.7

### ISSUE THREAD

**Issue by bferrell** [aabc/ipt-netflow#80]
Distro:  Scientific Linux 6.9

7 (detected from /sbin/iptables)
pkg-config for version 1.4.7 exists: Yes
Checking for presence of xtables.h... Yes (using pkg-config)
Iptables include flags:   (pkg-config)
Iptables module path: /lib64/xtables (pkg-config)
Searching for net-snmp-config... Yes /usr/bin/net-snmp-config
Searching for net-snmp agent... Yes.
Checking for DKMS... Yes.
! You are already have module installed via DKMS
!   it will be uninstalled on 'make install' and
!   current version of module installed afterwards.
! Use --disable-dkms option if don't want this.
Creating Makefile.. done.

  If you need some options enabled run ./configure --help
  Now run: make all install

[root@rr-v ipt-netflow-2.2]# make all
Compiling for kernel 4.12.7-1.el6.elrepo.x86_64
make -C /usr/src/kernels/4.12.7-1.el6.elrepo.x86_64/ M=/root/ipt-netflow-2.2 modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory `/usr/src/kernels/4.12.7-1.el6.elrepo.x86_64'
   CC [M]  /root/ipt-netflow-2.2/ipt_NETFLOW.o
/root/ipt-netflow-2.2/ipt_NETFLOW.c: In function ‘netflow_sendmsg’:
/root/ipt-netflow-2.2/ipt_NETFLOW.c:2002: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c: In function ‘netflow_export_flow_tpl’:
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3690: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c: In function ‘netflow_export_stats’:
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3853: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3853: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3853: error: type defaults to ‘int’ in declaration of ‘__x’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3853: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3853: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3853: error: type defaults to ‘int’ in declaration of ‘__y’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3853: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3854: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3854: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3854: error: type defaults to ‘int’ in declaration of ‘__UNIQUE_ID_max1_99’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3854: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3854: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3854: error: type defaults to ‘int’ in declaration of ‘__UNIQUE_ID_max2_100’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3854: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3855: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3855: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3855: error: type defaults to ‘int’ in declaration of ‘__x’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3855: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3855: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3855: error: type defaults to ‘int’ in declaration of ‘__y’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3855: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3856: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3856: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3856: error: type defaults to ‘int’ in declaration of ‘__UNIQUE_ID_max1_103’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3856: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3856: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3856: error: type defaults to ‘int’ in declaration of ‘__UNIQUE_ID_max2_104’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3856: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c: In function ‘ethtool_drvinfo’:
/root/ipt-netflow-2.2/ipt_NETFLOW.c:3936: error: implicit declaration of function ‘__ethtool_get_settings’
/root/ipt-netflow-2.2/ipt_NETFLOW.c: In function ‘netflow_target’:
/root/ipt-netflow-2.2/ipt_NETFLOW.c:4792: error: ‘const struct xt_action_param’ has no member named ‘family’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:4820: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:4831: error: ‘const struct xt_action_param’ has no member named ‘in’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:4831: error: ‘const struct xt_action_param’ has no member named ‘in’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:5068: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:5077: error: request for member ‘tv64’ in something not a structure or union
/root/ipt-netflow-2.2/ipt_NETFLOW.c:5090: error: ‘const struct xt_action_param’ has no member named ‘out’
/root/ipt-netflow-2.2/ipt_NETFLOW.c:5090: error: ‘const struct xt_action_param’ has no member named ‘out’
make[2]: *** [/root/ipt-netflow-2.2/ipt_NETFLOW.o] Error 1
make[1]: *** [_module_/root/ipt-netflow-2.2] Error 2
make[1]: Leaving directory `/usr/src/kernels/4.12.7-1.el6.elrepo.x86_64'
make: *** [ipt_NETFLOW.ko] Error 2

**Comment by k0ste** [comment]
@bferrell you should build from master. Release is outdated.

**Comment by aabc** [comment]
Yes, release is fixed on the date of the release, but kernel development continues, so you should use development version too, please clone from Github master. Current git head should compile up to Linux 4.13 (with the `.config` from Centos 7 at least).

**Comment by k0ste** [comment]
@aabc, may be this is time for release?
Last release support build up to 4.5.

**Comment by aabc** [comment]
@k0ste Maybe!

**Comment by bferrell** [comment]
You are correct.  build from master worked.  Thanks all!
