### ISSUE TITLE
Send option templates and data packets containing sampling information

### ISSUE THREAD

**Issue by taktv6** [aabc/ipt-netflow#82]
Hi there,

I might be wrong but from what I was able to see in packet dumps it seems ipt-NETFLOW doesn't send information about it's sampling configuration. Especially the configured sampling rate would be very interesting to me.

Thanks
takt

**Comment by aabc** [comment]
Hi,

It should send sampling configuration and statistics periodically (once per five minutes) when protocol is 9 or ipfix. What protocol and sampler you are using?

**Comment by taktv6** [comment]
Hi,

I use these settings:
root@bb-a.ix.dus.de.ffrl.de /proc/sys/net/netflow # cat protocol 
9
root@bb-a.ix.dus.de.ffrl.de /proc/sys/net/netflow # cat sampler 
hash:16

Will do another PCAP and have a closer look at it.

Thanks
takt

**Comment by taktv6** [comment]
Hi,

Nevermind. Just sniffed a few more packets and hat a closer look.
Found Option Template and SamplerID in the data flows. Works fine.

Thanks
Oliver
