### ISSUE TITLE
snmp-rules configure option seems broken

### ISSUE THREAD

**Issue by ednagrom** [aabc/ipt-netflow#84]
Hi, 
I'm trying to enable the snmp-rules option, but invoking the configure script with --enable-snmp-rules seems to do nothing.
When checking in the code, the --enable-snmp-rules enable the "ENABLE_SNMP" constant in the configure script, but the ipt_NETFLOW.c seems to check for the "SNMP_RULES" constant to enable the corresponding code.
When trying to change the configure script and replace the "ENABLE_SNMP" with "SNMP_RULES" for the --enable-snmp-rules option (line 338), the snmp-rules functionnality seems enabled (the option is shown in sysctl net.netflow after installation and activation of the module) , but there's a warning during compilation of ipt_NETFLOW.c : line 1113, the seq_printf don't have the proper argument number.
Is there really a problem with snmp-rules or am i  doing something wrong ?
thank you

**Comment by aabc** [comment]
You are right, and thanks for the report!
