### ISSUE TITLE
Can't make on 4.9 kernel.

### ISSUE THREAD

**Issue by GizmoV** [aabc/ipt-netflow#85]
/usr/src/ipt-netflow-2.2# make all
Compiling for kernel 4.9.51-v-ndpi+imq
make -C /lib/modules/4.9.51-v-ndpi+imq/build M=/usr/src/ipt-netflow-2.2 modules CONFIG_DEBUG_INFO=y
make[1]: Entering directory '/usr/src/linux-source-4.9'
  CC [M]  /usr/src/ipt-netflow-2.2/ipt_NETFLOW.o
/usr/src/ipt-netflow-2.2/ipt_NETFLOW.c: In function ‘ethtool_drvinfo’:
/usr/src/ipt-netflow-2.2/ipt_NETFLOW.c:3936:7: error: implicit declaration of function ‘__ethtool_get_settings’ [-Werror=implicit-function-declaration]
      !__ethtool_get_settings(dev, &ecmd)) {
       ^~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:304: recipe for target '/usr/src/ipt-netflow-2.2/ipt_NETFLOW.o' failed
make[2]: *** [/usr/src/ipt-netflow-2.2/ipt_NETFLOW.o] Error 1
Makefile:1510: recipe for target '_module_/usr/src/ipt-netflow-2.2' failed
make[1]: *** [_module_/usr/src/ipt-netflow-2.2] Error 2
make[1]: Leaving directory '/usr/src/linux-source-4.9'
Makefile:24: recipe for target 'ipt_NETFLOW.ko' failed
make: *** [ipt_NETFLOW.ko] Error 2

**Comment by GizmoV** [comment]
But all work's fine grom GIT.

**Comment by aabc** [comment]
4.9 wasn't existed when 2.2 was released, so kindly use git.

**Comment by k0ste** [comment]
4.6, 4.10 and 4.13. So may be new release and close this issues?

**Comment by aabc** [comment]
What '4.6, 4.10 and 4.13'?

**Comment by k0ste** [comment]
Unable to make release.

**Comment by tylerjl** [comment]
Howdy; I'm not sure whether you'd prefer a new issue for this or not, but here's the dkms install error message when attempting to install the module on kernel 4.14.4: 

```
In file included from /var/lib/dkms/ipt-netflow/r330.7f25426/build/ipt_NETFLOW.c:76:0:
/var/lib/dkms/ipt-netflow/r330.7f25426/build/ipt_NETFLOW.h:197:2: error: redeclaration of enumerator 'SCOPE_SYSTEM'
  SCOPE_SYSTEM = 1,
  ^~~~~~~~~~~~
In file included from ./arch/arm64/include/asm/hw_breakpoint.h:20:0,
                 from ./arch/arm64/include/asm/processor.h:34,
                 from ./arch/arm64/include/asm/spinlock.h:21,
                 from ./include/linux/spinlock.h:88,
                 from ./include/linux/seqlock.h:36,
                 from ./include/linux/time.h:6,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:10,
                 from /var/lib/dkms/ipt-netflow/r330.7f25426/build/ipt_NETFLOW.c:21:
./arch/arm64/include/asm/cpufeature.h:89:2: note: previous definition of 'SCOPE_SYSTEM' was here
  SCOPE_SYSTEM,
  ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:321: /var/lib/dkms/ipt-netflow/r330.7f25426/build/ipt_NETFLOW.o] Error 1
make[1]: *** [Makefile:1503: _module_/var/lib/dkms/ipt-netflow/r330.7f25426/build] Error 2
```

I'd love to be able to use this module, it really looks great! Thanks for still working to maintain compatibility with the latest kernels.

**Comment by tylerjl** [comment]
@aabc I built a new module from 0565def and can confirm the module works flawlessly on arm64 (specifically I'm on an espressobin). Thank you so much for resolving it so quickly, I really appreciate it!

**Comment by aabc** [comment]
Thanks.
