### ISSUE TITLE
missing packets

### ISSUE THREAD

**Issue by mgregr** [aabc/ipt-netflow#87]
I am mirroring traffic from a switch to a box with `ipt_NETFLOW 2.2-24-g0565def` on `CentOS 3.10.0-693.5.2.el7` with `promisc` mode on.  

I have configure the `iptables` and `ip6tables` with the following commands:

```
iptables -A PREROUTING -t raw -i eth1 -j NETFLOW
iptables -A PREROUTING -t raw -i eth2 -j NETFLOW
ip6tables -A PREROUTING -t raw -i eth1 -j NETFLOW
ip6tables -A PREROUTING -t raw -i eth2 -j NETFLOW
```
The sum of packets obtained from `iptables` and `ip6tables` counters match +- the pps reported by `ipt_NETFLOW`.  e.g. from last 5 min both iptables+ip6tables and ipt_NETFLOW says  ~416 Kpps .

I am monitoring stats from interfaces as well and I see around 100 Kpps higher packet rate, e.g. from the same time period, the sum of received packets on both interfaces was ~ 550 Kpps 

I don't see drops in `ipt_NETFLOW` and the number of packets dropped by NICs are neglible as well (around 50pps). Does anyone know what could be the reason for such a huge difference?

**Comment by aabc** [comment]
Do not look at pps counter, as this is just statistical estimator (EWMA). To be precise look at packet counters and measure their difference between points in time.

**Comment by igregr** [comment]
Yes, that's what I am doing. I am comparing `inPackets` stats from `ipt_netflow_snmp` with counters from `iptables + ip6tables`. That numbers match. `ipt_netflow` accounts everyhing what enters the iptables. However, taking `rx_packets`  stats from `ethtool -S eth0 + ethtool -S eth1` differs. The difference is about 100K packets.

**Comment by aabc** [comment]
So you have 100K pps of unknown traffic? This is not iptables/ipt-netflow related question - why you have non-ipv4/ipv6 packets in the network. If you think iptables don't see valid ipv4/ipv6 packets you should file bug to xtables.

There could be many non-ipv4/ipv4 packets: ARP, CDP, some non-decoded L2 encapsulation, like dot1q vlans, maybe just some buggy device noise/garbage.

Check your sysctl values for `net.bridge.bridge-nf-call-iptables`, `net.bridge.bridge-nf-call-ip6tables`, `net.bridge.bridge-nf-filter-vlan-tagged` and try setting them to `1`. See http://ebtables.netfilter.org/documentation/bridge-nf.html

**Comment by igregr** [comment]
It depends if it's unknow or not accounted properly for some reason. The whole traffic received on both interfaces is tagged using dot1q. Currently, stats on interfaces show 1.4Mpps. I see tags and ipt_netflow exports dot1q tags correctly. ipt_netflow and iptables reports 980 Kpps. If I run `tcpdump 'not ip not ip6'` to see non related ipv4/ipv6 traffic I have only few hundred pps of ARP traffic, definitely not 400 Kpps. Is there a way, how to find packets that did not enter to iptables?

I had to load `br_netfilter` module. After that, I set all values you mentioned to 1, but no difference.

**Comment by aabc** [comment]
Pls check `Promisc hack is enabled (observed X packets, discarded Y)` what these values accord to.

**Comment by igregr** [comment]
Yes, it is. 
```
ipt_NETFLOW 2.2-24-g0565def, srcversion 2853BAAF933603B5809DC4C; llist mac promisc vlan
Protocol version 9 (netflow), refresh-rate 20, timeout-rate 30, (templates 21, active 21).
Timeouts: active 30s, inactive 15s. Maxflows 2000000
Promisc hack is enabled (observed 33601073281 packets, discarded 71782).
Flows: active 411936 (peak 637667 reached 0d2h25m ago), mem 84845K, worker delay 1/1000 [1..100] (10 ms, 2000 us, 318:0 2 [cpu6]).
Hash: size 2621440 (mem 20480K), metric 1.11 [1.07, 1.00, 1.00]. InHash: 17765319 pkt, 25246812 K, InPDU 82, 46314.
Rate: 11382902586 bits/sec, 987102 packets/sec; Avg 1 min: 11560109176 bps, 1004872 pps; 5 min: 11351023646 bps, 991882 pps
cpu#     pps; <search found new [metric], trunc frag alloc maxflows>, traffic: <pkt, bytes>, drop: <pkt, bytes>
Total 987098; 2291007492 31957250610 909158045 [12.54],    0 448161    0    0, traffic: 32866408655, 39738047 MB, drop: 0, 0 K
cpu0  138416; 286015746 4232707254 113967927 [1.06],    0 4688    0    0, traffic: 4346675181, 5180153 MB, drop: 0, 0 K
cpu1  118305; 253932077 3675323883 113453949 [1.06],    0 7988    0    0, traffic: 3788777832, 4800575 MB, drop: 0, 0 K
cpu2  111885; 291531510 3994721898 113261805 [1.04],    0 5680    0    0, traffic: 4107983703, 5203068 MB, drop: 0, 0 K
cpu3  124781; 361196783 4115144090 113819459 [1.05],    0 5339    0    0, traffic: 4228963549, 4871177 MB, drop: 0, 0 K
cpu4  105606; 255278644 3782025210 113344205 [1.04],    0 8079    0    0, traffic: 3895369415, 4506657 MB, drop: 0, 0 K
cpu5  139190; 278733987 3935112388 113756210 [1.15],    0 402696    0    0, traffic: 4048868598, 4968975 MB, drop: 0, 0 K
cpu6  128545; 288638071 4167171566 113555469 [1.06],    0 8670    0    0, traffic: 4280727035, 5130669 MB, drop: 0, 0 K
cpu7  120370; 275680676 4055044338 113999021 [1.06],    0 5021    0    0, traffic: 4169043359, 5076768 MB, drop: 0, 0 K
Export: Rate 1503875 bytes/s; Total 42415077 pkts, 56188 MB, 908746092 flows; Errors 0 pkts; Traffic lost 0 pkts, 0 Kbytes, 0 flows.
sock0: x.x.3.134:9998, sndbuf 212992, filled 1, peak 52993; err: sndbuf reached 0, connect 0, cberr 0, other 0
```

Maybe it is interesting the higher total metric [12.54], although metric per cpu is around 1.

**Comment by aabc** [comment]
Check `Promisc hack is enabled (observed X packets, discarded Y)` line for X and Y values and see what they accord to - device counters or iptables counters.

**Comment by aabc** [comment]
Thanks.
