### ISSUE TITLE
Cross compilation failure

### ISSUE THREAD

**Issue by seablue** [aabc/ipt-netflow#88]
Compiler is hard coded to gcc. As a result, It's impossible to use the correct compiler for crossing compilation.

A simple fix is attached for your information. Thank you.

[fix.patch.txt](https://github.com/aabc/ipt-netflow/files/1669162/fix.patch.txt)

By the way, thanks for the brilliant work.

**Comment by aabc** [comment]
Thanks! Btw, how you compile so you can not redefine `CC` in `make` run? Normally you should be able to run `make CC=whatever-gcc`.

**Comment by seablue** [comment]
Yes, I tried #CC=whatever-gcc make ...
But I keep encountering an error. Then I checked the generated Makefile and found it always use local gcc. After I changed that, it works.

**Comment by aabc** [comment]
`make CC=whatever-gcc ...` not `CC=whatever-gcc make ...`.

**Comment by seablue** [comment]
Tried it. It works.

Thanks for telling me this.

**Comment by aabc** [comment]
Thanks!
