### ISSUE TITLE
centos 7 kernel 3.10

### ISSUE THREAD

**Issue by Magistr-Telecom** [aabc/ipt-netflow#92]
root@ ipt-netflow-2.2]# make CC=gcc-4.8.5
Compiling for kernel 3.10.0-693.17.1.el7.x86_64
make -C /lib/modules/3.10.0-693.17.1.el7.x86_64/build M=/home/mt/ipt-netflow-2.2 modules CONFIG_DEBUG_INFO=y
make[1]: Вход в каталог `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
arch/x86/Makefile:96: stack-protector enabled but compiler support broken
Makefile:641: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
make[1]: gcc-4.8.5: Команда не найдена
  CC [M]  /home/mt/ipt-netflow-2.2/ipt_NETFLOW.o
/bin/sh: gcc-4.8.5: команда не найдена
make[2]: *** [/home/mt/ipt-netflow-2.2/ipt_NETFLOW.o] Ошибка 127
make[1]: *** [_module_/home/mt/ipt-netflow-2.2] Ошибка 2
make[1]: Выход из каталога `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
make: *** [ipt_NETFLOW.ko] Ошибка 2
[root@ ipt-netflow-2.2]# make install
Compiling for kernel 3.10.0-693.17.1.el7.x86_64
make -C /lib/modules/3.10.0-693.17.1.el7.x86_64/build M=/home/mt/ipt-netflow-2.2 modules CONFIG_DEBUG_INFO=y
make[1]: Вход в каталог `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
  CC [M]  /home/mt/ipt-netflow-2.2/ipt_NETFLOW.o
/home/mt/ipt-netflow-2.2/ipt_NETFLOW.c: В функции «ethtool_drvinfo»:
/home/mt/ipt-netflow-2.2/ipt_NETFLOW.c:3935:6: ошибка: неявная декларация функции «__ethtool_get_settings» [-Werror=implicit-function-declaration]
      !__ethtool_get_settings(dev, &ecmd)) {
      ^
cc1: some warnings being treated as errors
make[2]: *** [/home/mt/ipt-netflow-2.2/ipt_NETFLOW.o] Ошибка 1
make[1]: *** [_module_/home/mt/ipt-netflow-2.2] Ошибка 2
make[1]: Выход из каталога `/usr/src/kernels/3.10.0-693.17.1.el7.x86_64'
make: *** [ipt_NETFLOW.ko] Ошибка 2
как исправить ошибку?

**Comment by Pinkbyte** [comment]
Проблема не с ipt_NETFLOW, проблема с тем что используется фича в конфиге ядра, которую не поддерживает указанный компилятор(gcc 4.8.5). -fstack-protector-strong поддерживается начиная с 4.9.3, ЕМНИП(по крайней мере так в Gentoo)

**Comment by Magistr-Telecom** [comment]
Спасибо

**Comment by aabc** [comment]
Пожалуйста, юзайте не релиз 2.2, а версию из git. Релиз 2.2 сделанный в феврале 2016 не может поддерживать ядра 2018 года, так как будущее не известно.

**Comment by aabc** [comment]
Release 2.3.
